<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Akka.Remote Microsoft.Extensions.Hosting support.</Description>
        <TargetFramework>$(NetStandardLibVersion)</TargetFramework>
        <Nullable>enable</Nullable>
        <PackageTags>$(AkkaPackageTags);hosting;remoting</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageProjectUrl>https://getakka.net/articles/hosting/index.html</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Akka.Hosting\Akka.Hosting.csproj" />
        <ProjectReference Include="..\..\..\core\Akka.Remote\Akka.Remote.csproj" />
    </ItemGroup>

</Project>
