<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Helper classes for combining the Akka.Remote.TestKit with Akka.Cluster</Description>
    <TargetFrameworks>$(NetStandardLibVersion);$(NetLibVersion)</TargetFrameworks>
    <PackageTags>$(AkkaPackageTags);network;cluster;testkit</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Remote.TestKit\Akka.Remote.TestKit.csproj" />
    <ProjectReference Include="..\Akka.Cluster\Akka.Cluster.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Akka.Cluster.TestKit.v3\FailureDetectorPuppet.cs">
      <Link>FailureDetectorPuppet.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Cluster.TestKit.v3\MultiNodeClusterSpec.cs">
      <Link>MultiNodeClusterSpec.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Cluster.TestKit.v3\MultiNodeLoggingConfig.cs">
      <Link>MultiNodeLoggingConfig.cs</Link>
    </Compile>
  </ItemGroup>

</Project>
