// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WireFormats.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akka.Remote.Serialization.Proto.Msg {

  /// <summary>Holder for reflection information generated from WireFormats.proto</summary>
  internal static partial class WireFormatsReflection {

    #region Descriptor
    /// <summary>File descriptor for WireFormats.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WireFormatsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFXaXJlRm9ybWF0cy5wcm90bxIjQWtrYS5SZW1vdGUuU2VyaWFsaXphdGlv",
            "bi5Qcm90by5Nc2caDUFkZHJlc3MucHJvdG8aDVBheWxvYWQucHJvdG8ipwEK",
            "F0Fja0FuZEVudmVsb3BlQ29udGFpbmVyEkUKA2FjaxgBIAEoCzI4LkFra2Eu",
            "UmVtb3RlLlNlcmlhbGl6YXRpb24uUHJvdG8uTXNnLkFja25vd2xlZGdlbWVu",
            "dEluZm8SRQoIZW52ZWxvcGUYAiABKAsyMy5Ba2thLlJlbW90ZS5TZXJpYWxp",
            "emF0aW9uLlByb3RvLk1zZy5SZW1vdGVFbnZlbG9wZSLlAQoOUmVtb3RlRW52",
            "ZWxvcGUSRAoJcmVjaXBpZW50GAEgASgLMjEuQWtrYS5SZW1vdGUuU2VyaWFs",
            "aXphdGlvbi5Qcm90by5Nc2cuQWN0b3JSZWZEYXRhEj0KB21lc3NhZ2UYAiAB",
            "KAsyLC5Ba2thLlJlbW90ZS5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5QYXls",
            "b2FkEkEKBnNlbmRlchgEIAEoCzIxLkFra2EuUmVtb3RlLlNlcmlhbGl6YXRp",
            "b24uUHJvdG8uTXNnLkFjdG9yUmVmRGF0YRILCgNzZXEYBSABKAYiOwoTQWNr",
            "bm93bGVkZ2VtZW50SW5mbxIVCg1jdW11bGF0aXZlQWNrGAEgASgGEg0KBW5h",
            "Y2tzGAIgAygGIhwKDEFjdG9yUmVmRGF0YRIMCgRwYXRoGAEgASgJIuoBChNE",
            "YWVtb25Nc2dDcmVhdGVEYXRhEj0KBXByb3BzGAEgASgLMi4uQWtrYS5SZW1v",
            "dGUuU2VyaWFsaXphdGlvbi5Qcm90by5Nc2cuUHJvcHNEYXRhEj8KBmRlcGxv",
            "eRgCIAEoCzIvLkFra2EuUmVtb3RlLlNlcmlhbGl6YXRpb24uUHJvdG8uTXNn",
            "LkRlcGxveURhdGESDAoEcGF0aBgDIAEoCRJFCgpzdXBlcnZpc29yGAQgASgL",
            "MjEuQWtrYS5SZW1vdGUuU2VyaWFsaXphdGlvbi5Qcm90by5Nc2cuQWN0b3JS",
            "ZWZEYXRhIqgBCglQcm9wc0RhdGESPwoGZGVwbG95GAIgASgLMi8uQWtrYS5S",
            "ZW1vdGUuU2VyaWFsaXphdGlvbi5Qcm90by5Nc2cuRGVwbG95RGF0YRINCgVj",
            "bGF6ehgDIAEoCRIMCgRhcmdzGAQgAygMEhEKCW1hbmlmZXN0cxgFIAMoCRIV",
            "Cg1zZXJpYWxpemVySWRzGAYgAygFEhMKC2hhc01hbmlmZXN0GAcgAygIIokC",
            "CgpEZXBsb3lEYXRhEgwKBHBhdGgYASABKAkSDgoGY29uZmlnGAIgASgMEhQK",
            "DHJvdXRlckNvbmZpZxgDIAEoDBINCgVzY29wZRgEIAEoDBISCgpkaXNwYXRj",
            "aGVyGAUgASgJEhkKEXNjb3BlU2VyaWFsaXplcklkGAYgASgFEhUKDXNjb3Bl",
            "TWFuaWZlc3QYByABKAkSGgoSY29uZmlnU2VyaWFsaXplcklkGAggASgFEhYK",
            "DmNvbmZpZ01hbmlmZXN0GAkgASgJEiAKGHJvdXRlckNvbmZpZ1NlcmlhbGl6",
            "ZXJJZBgKIAEoBRIcChRyb3V0ZXJDb25maWdNYW5pZmVzdBgLIAEoCSJ0ChNB",
            "a2thUHJvdG9jb2xNZXNzYWdlEg8KB3BheWxvYWQYASABKAwSTAoLaW5zdHJ1",
            "Y3Rpb24YAiABKAsyNy5Ba2thLlJlbW90ZS5TZXJpYWxpemF0aW9uLlByb3Rv",
            "Lk1zZy5Ba2thQ29udHJvbE1lc3NhZ2UiqgEKEkFra2FDb250cm9sTWVzc2Fn",
            "ZRJFCgtjb21tYW5kVHlwZRgBIAEoDjIwLkFra2EuUmVtb3RlLlNlcmlhbGl6",
            "YXRpb24uUHJvdG8uTXNnLkNvbW1hbmRUeXBlEk0KDWhhbmRzaGFrZUluZm8Y",
            "AiABKAsyNi5Ba2thLlJlbW90ZS5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5B",
            "a2thSGFuZHNoYWtlSW5mbyJuChFBa2thSGFuZHNoYWtlSW5mbxI8CgZvcmln",
            "aW4YASABKAsyLC5Ba2thLlJlbW90ZS5TZXJpYWxpemF0aW9uLlByb3RvLk1z",
            "Zy5BZGRyZXNzEgsKA3VpZBgCIAEoBhIOCgZjb29raWUYAyABKAkqhQEKC0Nv",
            "bW1hbmRUeXBlEggKBE5PTkUQABINCglBU1NPQ0lBVEUQARIQCgxESVNBU1NP",
            "Q0lBVEUQAhINCglIRUFSVEJFQVQQAxIeChpESVNBU1NPQ0lBVEVfU0hVVFRJ",
            "TkdfRE9XThAEEhwKGERJU0FTU09DSUFURV9RVUFSQU5USU5FRBAFQgJIAWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Akka.Remote.Serialization.Proto.Msg.AddressReflection.Descriptor, global::Akka.Remote.Serialization.Proto.Msg.PayloadReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Akka.Remote.Serialization.Proto.Msg.CommandType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.AckAndEnvelopeContainer), global::Akka.Remote.Serialization.Proto.Msg.AckAndEnvelopeContainer.Parser, new[]{ "Ack", "Envelope" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.RemoteEnvelope), global::Akka.Remote.Serialization.Proto.Msg.RemoteEnvelope.Parser, new[]{ "Recipient", "Message", "Sender", "Seq" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.AcknowledgementInfo), global::Akka.Remote.Serialization.Proto.Msg.AcknowledgementInfo.Parser, new[]{ "CumulativeAck", "Nacks" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.ActorRefData), global::Akka.Remote.Serialization.Proto.Msg.ActorRefData.Parser, new[]{ "Path" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.DaemonMsgCreateData), global::Akka.Remote.Serialization.Proto.Msg.DaemonMsgCreateData.Parser, new[]{ "Props", "Deploy", "Path", "Supervisor" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.PropsData), global::Akka.Remote.Serialization.Proto.Msg.PropsData.Parser, new[]{ "Deploy", "Clazz", "Args", "Manifests", "SerializerIds", "HasManifest" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.DeployData), global::Akka.Remote.Serialization.Proto.Msg.DeployData.Parser, new[]{ "Path", "Config", "RouterConfig", "Scope", "Dispatcher", "ScopeSerializerId", "ScopeManifest", "ConfigSerializerId", "ConfigManifest", "RouterConfigSerializerId", "RouterConfigManifest" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.AkkaProtocolMessage), global::Akka.Remote.Serialization.Proto.Msg.AkkaProtocolMessage.Parser, new[]{ "Payload", "Instruction" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.AkkaControlMessage), global::Akka.Remote.Serialization.Proto.Msg.AkkaControlMessage.Parser, new[]{ "CommandType", "HandshakeInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Remote.Serialization.Proto.Msg.AkkaHandshakeInfo), global::Akka.Remote.Serialization.Proto.Msg.AkkaHandshakeInfo.Parser, new[]{ "Origin", "Uid", "Cookie" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Defines the type of the AkkaControlMessage command type
  /// </summary>
  internal enum CommandType {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("ASSOCIATE")] Associate = 1,
    [pbr::OriginalName("DISASSOCIATE")] Disassociate = 2,
    [pbr::OriginalName("HEARTBEAT")] Heartbeat = 3,
    /// <summary>
    /// Remote system is going down and will not accepts new connections
    /// </summary>
    [pbr::OriginalName("DISASSOCIATE_SHUTTING_DOWN")] DisassociateShuttingDown = 4,
    /// <summary>
    /// Remote system refused the association since the current system is quarantined
    /// </summary>
    [pbr::OriginalName("DISASSOCIATE_QUARANTINED")] DisassociateQuarantined = 5,
  }

  #endregion

  #region Messages
  internal sealed partial class AckAndEnvelopeContainer : pb::IMessage<AckAndEnvelopeContainer> {
    private static readonly pb::MessageParser<AckAndEnvelopeContainer> _parser = new pb::MessageParser<AckAndEnvelopeContainer>(() => new AckAndEnvelopeContainer());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AckAndEnvelopeContainer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AckAndEnvelopeContainer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AckAndEnvelopeContainer(AckAndEnvelopeContainer other) : this() {
      Ack = other.ack_ != null ? other.Ack.Clone() : null;
      Envelope = other.envelope_ != null ? other.Envelope.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AckAndEnvelopeContainer Clone() {
      return new AckAndEnvelopeContainer(this);
    }

    /// <summary>Field number for the "ack" field.</summary>
    public const int AckFieldNumber = 1;
    private global::Akka.Remote.Serialization.Proto.Msg.AcknowledgementInfo ack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.AcknowledgementInfo Ack {
      get { return ack_; }
      set {
        ack_ = value;
      }
    }

    /// <summary>Field number for the "envelope" field.</summary>
    public const int EnvelopeFieldNumber = 2;
    private global::Akka.Remote.Serialization.Proto.Msg.RemoteEnvelope envelope_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.RemoteEnvelope Envelope {
      get { return envelope_; }
      set {
        envelope_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AckAndEnvelopeContainer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AckAndEnvelopeContainer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Ack, other.Ack)) return false;
      if (!object.Equals(Envelope, other.Envelope)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ack_ != null) hash ^= Ack.GetHashCode();
      if (envelope_ != null) hash ^= Envelope.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ack_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Ack);
      }
      if (envelope_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Envelope);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ack);
      }
      if (envelope_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Envelope);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AckAndEnvelopeContainer other) {
      if (other == null) {
        return;
      }
      if (other.ack_ != null) {
        if (ack_ == null) {
          ack_ = new global::Akka.Remote.Serialization.Proto.Msg.AcknowledgementInfo();
        }
        Ack.MergeFrom(other.Ack);
      }
      if (other.envelope_ != null) {
        if (envelope_ == null) {
          envelope_ = new global::Akka.Remote.Serialization.Proto.Msg.RemoteEnvelope();
        }
        Envelope.MergeFrom(other.Envelope);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (ack_ == null) {
              ack_ = new global::Akka.Remote.Serialization.Proto.Msg.AcknowledgementInfo();
            }
            input.ReadMessage(ack_);
            break;
          }
          case 18: {
            if (envelope_ == null) {
              envelope_ = new global::Akka.Remote.Serialization.Proto.Msg.RemoteEnvelope();
            }
            input.ReadMessage(envelope_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Defines a remote message.
  /// </summary>
  internal sealed partial class RemoteEnvelope : pb::IMessage<RemoteEnvelope> {
    private static readonly pb::MessageParser<RemoteEnvelope> _parser = new pb::MessageParser<RemoteEnvelope>(() => new RemoteEnvelope());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemoteEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoteEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoteEnvelope(RemoteEnvelope other) : this() {
      Recipient = other.recipient_ != null ? other.Recipient.Clone() : null;
      Message = other.message_ != null ? other.Message.Clone() : null;
      Sender = other.sender_ != null ? other.Sender.Clone() : null;
      seq_ = other.seq_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoteEnvelope Clone() {
      return new RemoteEnvelope(this);
    }

    /// <summary>Field number for the "recipient" field.</summary>
    public const int RecipientFieldNumber = 1;
    private global::Akka.Remote.Serialization.Proto.Msg.ActorRefData recipient_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.ActorRefData Recipient {
      get { return recipient_; }
      set {
        recipient_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private global::Akka.Remote.Serialization.Proto.Msg.Payload message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.Payload Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 4;
    private global::Akka.Remote.Serialization.Proto.Msg.ActorRefData sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.ActorRefData Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 5;
    private ulong seq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemoteEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemoteEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Recipient, other.Recipient)) return false;
      if (!object.Equals(Message, other.Message)) return false;
      if (!object.Equals(Sender, other.Sender)) return false;
      if (Seq != other.Seq) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (recipient_ != null) hash ^= Recipient.GetHashCode();
      if (message_ != null) hash ^= Message.GetHashCode();
      if (sender_ != null) hash ^= Sender.GetHashCode();
      if (Seq != 0UL) hash ^= Seq.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (recipient_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Recipient);
      }
      if (message_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Message);
      }
      if (sender_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Sender);
      }
      if (Seq != 0UL) {
        output.WriteRawTag(41);
        output.WriteFixed64(Seq);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (recipient_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Recipient);
      }
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (sender_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sender);
      }
      if (Seq != 0UL) {
        size += 1 + 8;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemoteEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.recipient_ != null) {
        if (recipient_ == null) {
          recipient_ = new global::Akka.Remote.Serialization.Proto.Msg.ActorRefData();
        }
        Recipient.MergeFrom(other.Recipient);
      }
      if (other.message_ != null) {
        if (message_ == null) {
          message_ = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
        }
        Message.MergeFrom(other.Message);
      }
      if (other.sender_ != null) {
        if (sender_ == null) {
          sender_ = new global::Akka.Remote.Serialization.Proto.Msg.ActorRefData();
        }
        Sender.MergeFrom(other.Sender);
      }
      if (other.Seq != 0UL) {
        Seq = other.Seq;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (recipient_ == null) {
              recipient_ = new global::Akka.Remote.Serialization.Proto.Msg.ActorRefData();
            }
            input.ReadMessage(recipient_);
            break;
          }
          case 18: {
            if (message_ == null) {
              message_ = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
            }
            input.ReadMessage(message_);
            break;
          }
          case 34: {
            if (sender_ == null) {
              sender_ = new global::Akka.Remote.Serialization.Proto.Msg.ActorRefData();
            }
            input.ReadMessage(sender_);
            break;
          }
          case 41: {
            Seq = input.ReadFixed64();
            break;
          }
        }
      }
    }

  }

  internal sealed partial class AcknowledgementInfo : pb::IMessage<AcknowledgementInfo> {
    private static readonly pb::MessageParser<AcknowledgementInfo> _parser = new pb::MessageParser<AcknowledgementInfo>(() => new AcknowledgementInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AcknowledgementInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcknowledgementInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcknowledgementInfo(AcknowledgementInfo other) : this() {
      cumulativeAck_ = other.cumulativeAck_;
      nacks_ = other.nacks_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcknowledgementInfo Clone() {
      return new AcknowledgementInfo(this);
    }

    /// <summary>Field number for the "cumulativeAck" field.</summary>
    public const int CumulativeAckFieldNumber = 1;
    private ulong cumulativeAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong CumulativeAck {
      get { return cumulativeAck_; }
      set {
        cumulativeAck_ = value;
      }
    }

    /// <summary>Field number for the "nacks" field.</summary>
    public const int NacksFieldNumber = 2;
    private static readonly pb::FieldCodec<ulong> _repeated_nacks_codec
        = pb::FieldCodec.ForFixed64(18);
    private readonly pbc::RepeatedField<ulong> nacks_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> Nacks {
      get { return nacks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AcknowledgementInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AcknowledgementInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CumulativeAck != other.CumulativeAck) return false;
      if(!nacks_.Equals(other.nacks_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CumulativeAck != 0UL) hash ^= CumulativeAck.GetHashCode();
      hash ^= nacks_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CumulativeAck != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(CumulativeAck);
      }
      nacks_.WriteTo(output, _repeated_nacks_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CumulativeAck != 0UL) {
        size += 1 + 8;
      }
      size += nacks_.CalculateSize(_repeated_nacks_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AcknowledgementInfo other) {
      if (other == null) {
        return;
      }
      if (other.CumulativeAck != 0UL) {
        CumulativeAck = other.CumulativeAck;
      }
      nacks_.Add(other.nacks_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 9: {
            CumulativeAck = input.ReadFixed64();
            break;
          }
          case 18:
          case 17: {
            nacks_.AddEntriesFrom(input, _repeated_nacks_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Defines a remote ActorRef that "remembers" and uses its original Actor instance on the original node.
  /// </summary>
  internal sealed partial class ActorRefData : pb::IMessage<ActorRefData> {
    private static readonly pb::MessageParser<ActorRefData> _parser = new pb::MessageParser<ActorRefData>(() => new ActorRefData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActorRefData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorRefData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorRefData(ActorRefData other) : this() {
      path_ = other.path_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActorRefData Clone() {
      return new ActorRefData(this);
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 1;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActorRefData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActorRefData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Path != other.Path) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Path.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Path);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActorRefData other) {
      if (other == null) {
        return;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Path = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Defines Akka.Remote.DaemonMsgCreate
  /// </summary>
  internal sealed partial class DaemonMsgCreateData : pb::IMessage<DaemonMsgCreateData> {
    private static readonly pb::MessageParser<DaemonMsgCreateData> _parser = new pb::MessageParser<DaemonMsgCreateData>(() => new DaemonMsgCreateData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DaemonMsgCreateData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DaemonMsgCreateData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DaemonMsgCreateData(DaemonMsgCreateData other) : this() {
      Props = other.props_ != null ? other.Props.Clone() : null;
      Deploy = other.deploy_ != null ? other.Deploy.Clone() : null;
      path_ = other.path_;
      Supervisor = other.supervisor_ != null ? other.Supervisor.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DaemonMsgCreateData Clone() {
      return new DaemonMsgCreateData(this);
    }

    /// <summary>Field number for the "props" field.</summary>
    public const int PropsFieldNumber = 1;
    private global::Akka.Remote.Serialization.Proto.Msg.PropsData props_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.PropsData Props {
      get { return props_; }
      set {
        props_ = value;
      }
    }

    /// <summary>Field number for the "deploy" field.</summary>
    public const int DeployFieldNumber = 2;
    private global::Akka.Remote.Serialization.Proto.Msg.DeployData deploy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.DeployData Deploy {
      get { return deploy_; }
      set {
        deploy_ = value;
      }
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 3;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "supervisor" field.</summary>
    public const int SupervisorFieldNumber = 4;
    private global::Akka.Remote.Serialization.Proto.Msg.ActorRefData supervisor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.ActorRefData Supervisor {
      get { return supervisor_; }
      set {
        supervisor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DaemonMsgCreateData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DaemonMsgCreateData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Props, other.Props)) return false;
      if (!object.Equals(Deploy, other.Deploy)) return false;
      if (Path != other.Path) return false;
      if (!object.Equals(Supervisor, other.Supervisor)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (props_ != null) hash ^= Props.GetHashCode();
      if (deploy_ != null) hash ^= Deploy.GetHashCode();
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (supervisor_ != null) hash ^= Supervisor.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (props_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Props);
      }
      if (deploy_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Deploy);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (supervisor_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Supervisor);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (props_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Props);
      }
      if (deploy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Deploy);
      }
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (supervisor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Supervisor);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DaemonMsgCreateData other) {
      if (other == null) {
        return;
      }
      if (other.props_ != null) {
        if (props_ == null) {
          props_ = new global::Akka.Remote.Serialization.Proto.Msg.PropsData();
        }
        Props.MergeFrom(other.Props);
      }
      if (other.deploy_ != null) {
        if (deploy_ == null) {
          deploy_ = new global::Akka.Remote.Serialization.Proto.Msg.DeployData();
        }
        Deploy.MergeFrom(other.Deploy);
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.supervisor_ != null) {
        if (supervisor_ == null) {
          supervisor_ = new global::Akka.Remote.Serialization.Proto.Msg.ActorRefData();
        }
        Supervisor.MergeFrom(other.Supervisor);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (props_ == null) {
              props_ = new global::Akka.Remote.Serialization.Proto.Msg.PropsData();
            }
            input.ReadMessage(props_);
            break;
          }
          case 18: {
            if (deploy_ == null) {
              deploy_ = new global::Akka.Remote.Serialization.Proto.Msg.DeployData();
            }
            input.ReadMessage(deploy_);
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 34: {
            if (supervisor_ == null) {
              supervisor_ = new global::Akka.Remote.Serialization.Proto.Msg.ActorRefData();
            }
            input.ReadMessage(supervisor_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Serialization of Akka.Actor.Props
  /// </summary>
  internal sealed partial class PropsData : pb::IMessage<PropsData> {
    private static readonly pb::MessageParser<PropsData> _parser = new pb::MessageParser<PropsData>(() => new PropsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PropsData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PropsData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PropsData(PropsData other) : this() {
      Deploy = other.deploy_ != null ? other.Deploy.Clone() : null;
      clazz_ = other.clazz_;
      args_ = other.args_.Clone();
      manifests_ = other.manifests_.Clone();
      serializerIds_ = other.serializerIds_.Clone();
      hasManifest_ = other.hasManifest_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PropsData Clone() {
      return new PropsData(this);
    }

    /// <summary>Field number for the "deploy" field.</summary>
    public const int DeployFieldNumber = 2;
    private global::Akka.Remote.Serialization.Proto.Msg.DeployData deploy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.DeployData Deploy {
      get { return deploy_; }
      set {
        deploy_ = value;
      }
    }

    /// <summary>Field number for the "clazz" field.</summary>
    public const int ClazzFieldNumber = 3;
    private string clazz_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Clazz {
      get { return clazz_; }
      set {
        clazz_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "args" field.</summary>
    public const int ArgsFieldNumber = 4;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_args_codec
        = pb::FieldCodec.ForBytes(34);
    private readonly pbc::RepeatedField<pb::ByteString> args_ = new pbc::RepeatedField<pb::ByteString>();
    /// <summary>
    /// serialized props parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> Args {
      get { return args_; }
    }

    /// <summary>Field number for the "manifests" field.</summary>
    public const int ManifestsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_manifests_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> manifests_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// contains string manifest for each arg
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Manifests {
      get { return manifests_; }
    }

    /// <summary>Field number for the "serializerIds" field.</summary>
    public const int SerializerIdsFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_serializerIds_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> serializerIds_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// serializer id for each arg
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> SerializerIds {
      get { return serializerIds_; }
    }

    /// <summary>Field number for the "hasManifest" field.</summary>
    public const int HasManifestFieldNumber = 7;
    private static readonly pb::FieldCodec<bool> _repeated_hasManifest_codec
        = pb::FieldCodec.ForBool(58);
    private readonly pbc::RepeatedField<bool> hasManifest_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<bool> HasManifest {
      get { return hasManifest_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PropsData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PropsData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Deploy, other.Deploy)) return false;
      if (Clazz != other.Clazz) return false;
      if(!args_.Equals(other.args_)) return false;
      if(!manifests_.Equals(other.manifests_)) return false;
      if(!serializerIds_.Equals(other.serializerIds_)) return false;
      if(!hasManifest_.Equals(other.hasManifest_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (deploy_ != null) hash ^= Deploy.GetHashCode();
      if (Clazz.Length != 0) hash ^= Clazz.GetHashCode();
      hash ^= args_.GetHashCode();
      hash ^= manifests_.GetHashCode();
      hash ^= serializerIds_.GetHashCode();
      hash ^= hasManifest_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (deploy_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Deploy);
      }
      if (Clazz.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Clazz);
      }
      args_.WriteTo(output, _repeated_args_codec);
      manifests_.WriteTo(output, _repeated_manifests_codec);
      serializerIds_.WriteTo(output, _repeated_serializerIds_codec);
      hasManifest_.WriteTo(output, _repeated_hasManifest_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (deploy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Deploy);
      }
      if (Clazz.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Clazz);
      }
      size += args_.CalculateSize(_repeated_args_codec);
      size += manifests_.CalculateSize(_repeated_manifests_codec);
      size += serializerIds_.CalculateSize(_repeated_serializerIds_codec);
      size += hasManifest_.CalculateSize(_repeated_hasManifest_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PropsData other) {
      if (other == null) {
        return;
      }
      if (other.deploy_ != null) {
        if (deploy_ == null) {
          deploy_ = new global::Akka.Remote.Serialization.Proto.Msg.DeployData();
        }
        Deploy.MergeFrom(other.Deploy);
      }
      if (other.Clazz.Length != 0) {
        Clazz = other.Clazz;
      }
      args_.Add(other.args_);
      manifests_.Add(other.manifests_);
      serializerIds_.Add(other.serializerIds_);
      hasManifest_.Add(other.hasManifest_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            if (deploy_ == null) {
              deploy_ = new global::Akka.Remote.Serialization.Proto.Msg.DeployData();
            }
            input.ReadMessage(deploy_);
            break;
          }
          case 26: {
            Clazz = input.ReadString();
            break;
          }
          case 34: {
            args_.AddEntriesFrom(input, _repeated_args_codec);
            break;
          }
          case 42: {
            manifests_.AddEntriesFrom(input, _repeated_manifests_codec);
            break;
          }
          case 50:
          case 48: {
            serializerIds_.AddEntriesFrom(input, _repeated_serializerIds_codec);
            break;
          }
          case 58:
          case 56: {
            hasManifest_.AddEntriesFrom(input, _repeated_hasManifest_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Serialization of akka.actor.Deploy
  /// </summary>
  internal sealed partial class DeployData : pb::IMessage<DeployData> {
    private static readonly pb::MessageParser<DeployData> _parser = new pb::MessageParser<DeployData>(() => new DeployData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeployData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeployData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeployData(DeployData other) : this() {
      path_ = other.path_;
      config_ = other.config_;
      routerConfig_ = other.routerConfig_;
      scope_ = other.scope_;
      dispatcher_ = other.dispatcher_;
      scopeSerializerId_ = other.scopeSerializerId_;
      scopeManifest_ = other.scopeManifest_;
      configSerializerId_ = other.configSerializerId_;
      configManifest_ = other.configManifest_;
      routerConfigSerializerId_ = other.routerConfigSerializerId_;
      routerConfigManifest_ = other.routerConfigManifest_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeployData Clone() {
      return new DeployData(this);
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 1;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 2;
    private pb::ByteString config_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Config {
      get { return config_; }
      set {
        config_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routerConfig" field.</summary>
    public const int RouterConfigFieldNumber = 3;
    private pb::ByteString routerConfig_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString RouterConfig {
      get { return routerConfig_; }
      set {
        routerConfig_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scope" field.</summary>
    public const int ScopeFieldNumber = 4;
    private pb::ByteString scope_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Scope {
      get { return scope_; }
      set {
        scope_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dispatcher" field.</summary>
    public const int DispatcherFieldNumber = 5;
    private string dispatcher_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Dispatcher {
      get { return dispatcher_; }
      set {
        dispatcher_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scopeSerializerId" field.</summary>
    public const int ScopeSerializerIdFieldNumber = 6;
    private int scopeSerializerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ScopeSerializerId {
      get { return scopeSerializerId_; }
      set {
        scopeSerializerId_ = value;
      }
    }

    /// <summary>Field number for the "scopeManifest" field.</summary>
    public const int ScopeManifestFieldNumber = 7;
    private string scopeManifest_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ScopeManifest {
      get { return scopeManifest_; }
      set {
        scopeManifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "configSerializerId" field.</summary>
    public const int ConfigSerializerIdFieldNumber = 8;
    private int configSerializerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfigSerializerId {
      get { return configSerializerId_; }
      set {
        configSerializerId_ = value;
      }
    }

    /// <summary>Field number for the "configManifest" field.</summary>
    public const int ConfigManifestFieldNumber = 9;
    private string configManifest_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConfigManifest {
      get { return configManifest_; }
      set {
        configManifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routerConfigSerializerId" field.</summary>
    public const int RouterConfigSerializerIdFieldNumber = 10;
    private int routerConfigSerializerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RouterConfigSerializerId {
      get { return routerConfigSerializerId_; }
      set {
        routerConfigSerializerId_ = value;
      }
    }

    /// <summary>Field number for the "routerConfigManifest" field.</summary>
    public const int RouterConfigManifestFieldNumber = 11;
    private string routerConfigManifest_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RouterConfigManifest {
      get { return routerConfigManifest_; }
      set {
        routerConfigManifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeployData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeployData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Path != other.Path) return false;
      if (Config != other.Config) return false;
      if (RouterConfig != other.RouterConfig) return false;
      if (Scope != other.Scope) return false;
      if (Dispatcher != other.Dispatcher) return false;
      if (ScopeSerializerId != other.ScopeSerializerId) return false;
      if (ScopeManifest != other.ScopeManifest) return false;
      if (ConfigSerializerId != other.ConfigSerializerId) return false;
      if (ConfigManifest != other.ConfigManifest) return false;
      if (RouterConfigSerializerId != other.RouterConfigSerializerId) return false;
      if (RouterConfigManifest != other.RouterConfigManifest) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (Config.Length != 0) hash ^= Config.GetHashCode();
      if (RouterConfig.Length != 0) hash ^= RouterConfig.GetHashCode();
      if (Scope.Length != 0) hash ^= Scope.GetHashCode();
      if (Dispatcher.Length != 0) hash ^= Dispatcher.GetHashCode();
      if (ScopeSerializerId != 0) hash ^= ScopeSerializerId.GetHashCode();
      if (ScopeManifest.Length != 0) hash ^= ScopeManifest.GetHashCode();
      if (ConfigSerializerId != 0) hash ^= ConfigSerializerId.GetHashCode();
      if (ConfigManifest.Length != 0) hash ^= ConfigManifest.GetHashCode();
      if (RouterConfigSerializerId != 0) hash ^= RouterConfigSerializerId.GetHashCode();
      if (RouterConfigManifest.Length != 0) hash ^= RouterConfigManifest.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Path.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Path);
      }
      if (Config.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Config);
      }
      if (RouterConfig.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(RouterConfig);
      }
      if (Scope.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Scope);
      }
      if (Dispatcher.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Dispatcher);
      }
      if (ScopeSerializerId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ScopeSerializerId);
      }
      if (ScopeManifest.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ScopeManifest);
      }
      if (ConfigSerializerId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(ConfigSerializerId);
      }
      if (ConfigManifest.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ConfigManifest);
      }
      if (RouterConfigSerializerId != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(RouterConfigSerializerId);
      }
      if (RouterConfigManifest.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(RouterConfigManifest);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (Config.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Config);
      }
      if (RouterConfig.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RouterConfig);
      }
      if (Scope.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Scope);
      }
      if (Dispatcher.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Dispatcher);
      }
      if (ScopeSerializerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ScopeSerializerId);
      }
      if (ScopeManifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeManifest);
      }
      if (ConfigSerializerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfigSerializerId);
      }
      if (ConfigManifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConfigManifest);
      }
      if (RouterConfigSerializerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RouterConfigSerializerId);
      }
      if (RouterConfigManifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RouterConfigManifest);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeployData other) {
      if (other == null) {
        return;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.Config.Length != 0) {
        Config = other.Config;
      }
      if (other.RouterConfig.Length != 0) {
        RouterConfig = other.RouterConfig;
      }
      if (other.Scope.Length != 0) {
        Scope = other.Scope;
      }
      if (other.Dispatcher.Length != 0) {
        Dispatcher = other.Dispatcher;
      }
      if (other.ScopeSerializerId != 0) {
        ScopeSerializerId = other.ScopeSerializerId;
      }
      if (other.ScopeManifest.Length != 0) {
        ScopeManifest = other.ScopeManifest;
      }
      if (other.ConfigSerializerId != 0) {
        ConfigSerializerId = other.ConfigSerializerId;
      }
      if (other.ConfigManifest.Length != 0) {
        ConfigManifest = other.ConfigManifest;
      }
      if (other.RouterConfigSerializerId != 0) {
        RouterConfigSerializerId = other.RouterConfigSerializerId;
      }
      if (other.RouterConfigManifest.Length != 0) {
        RouterConfigManifest = other.RouterConfigManifest;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Path = input.ReadString();
            break;
          }
          case 18: {
            Config = input.ReadBytes();
            break;
          }
          case 26: {
            RouterConfig = input.ReadBytes();
            break;
          }
          case 34: {
            Scope = input.ReadBytes();
            break;
          }
          case 42: {
            Dispatcher = input.ReadString();
            break;
          }
          case 48: {
            ScopeSerializerId = input.ReadInt32();
            break;
          }
          case 58: {
            ScopeManifest = input.ReadString();
            break;
          }
          case 64: {
            ConfigSerializerId = input.ReadInt32();
            break;
          }
          case 74: {
            ConfigManifest = input.ReadString();
            break;
          }
          case 80: {
            RouterConfigSerializerId = input.ReadInt32();
            break;
          }
          case 90: {
            RouterConfigManifest = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Message format of Akka Protocol. Message contains either a payload or an instruction.
  /// </summary>
  internal sealed partial class AkkaProtocolMessage : pb::IMessage<AkkaProtocolMessage> {
    private static readonly pb::MessageParser<AkkaProtocolMessage> _parser = new pb::MessageParser<AkkaProtocolMessage>(() => new AkkaProtocolMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AkkaProtocolMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaProtocolMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaProtocolMessage(AkkaProtocolMessage other) : this() {
      payload_ = other.payload_;
      Instruction = other.instruction_ != null ? other.Instruction.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaProtocolMessage Clone() {
      return new AkkaProtocolMessage(this);
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 1;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "instruction" field.</summary>
    public const int InstructionFieldNumber = 2;
    private global::Akka.Remote.Serialization.Proto.Msg.AkkaControlMessage instruction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.AkkaControlMessage Instruction {
      get { return instruction_; }
      set {
        instruction_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AkkaProtocolMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AkkaProtocolMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Payload != other.Payload) return false;
      if (!object.Equals(Instruction, other.Instruction)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (instruction_ != null) hash ^= Instruction.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Payload.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Payload);
      }
      if (instruction_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Instruction);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (instruction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Instruction);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AkkaProtocolMessage other) {
      if (other == null) {
        return;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      if (other.instruction_ != null) {
        if (instruction_ == null) {
          instruction_ = new global::Akka.Remote.Serialization.Proto.Msg.AkkaControlMessage();
        }
        Instruction.MergeFrom(other.Instruction);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Payload = input.ReadBytes();
            break;
          }
          case 18: {
            if (instruction_ == null) {
              instruction_ = new global::Akka.Remote.Serialization.Proto.Msg.AkkaControlMessage();
            }
            input.ReadMessage(instruction_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Defines some control messages for the remoting
  /// </summary>
  internal sealed partial class AkkaControlMessage : pb::IMessage<AkkaControlMessage> {
    private static readonly pb::MessageParser<AkkaControlMessage> _parser = new pb::MessageParser<AkkaControlMessage>(() => new AkkaControlMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AkkaControlMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaControlMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaControlMessage(AkkaControlMessage other) : this() {
      commandType_ = other.commandType_;
      HandshakeInfo = other.handshakeInfo_ != null ? other.HandshakeInfo.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaControlMessage Clone() {
      return new AkkaControlMessage(this);
    }

    /// <summary>Field number for the "commandType" field.</summary>
    public const int CommandTypeFieldNumber = 1;
    private global::Akka.Remote.Serialization.Proto.Msg.CommandType commandType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.CommandType CommandType {
      get { return commandType_; }
      set {
        commandType_ = value;
      }
    }

    /// <summary>Field number for the "handshakeInfo" field.</summary>
    public const int HandshakeInfoFieldNumber = 2;
    private global::Akka.Remote.Serialization.Proto.Msg.AkkaHandshakeInfo handshakeInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.AkkaHandshakeInfo HandshakeInfo {
      get { return handshakeInfo_; }
      set {
        handshakeInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AkkaControlMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AkkaControlMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CommandType != other.CommandType) return false;
      if (!object.Equals(HandshakeInfo, other.HandshakeInfo)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CommandType != 0) hash ^= CommandType.GetHashCode();
      if (handshakeInfo_ != null) hash ^= HandshakeInfo.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CommandType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) CommandType);
      }
      if (handshakeInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HandshakeInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CommandType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CommandType);
      }
      if (handshakeInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HandshakeInfo);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AkkaControlMessage other) {
      if (other == null) {
        return;
      }
      if (other.CommandType != 0) {
        CommandType = other.CommandType;
      }
      if (other.handshakeInfo_ != null) {
        if (handshakeInfo_ == null) {
          handshakeInfo_ = new global::Akka.Remote.Serialization.Proto.Msg.AkkaHandshakeInfo();
        }
        HandshakeInfo.MergeFrom(other.HandshakeInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            commandType_ = (global::Akka.Remote.Serialization.Proto.Msg.CommandType) input.ReadEnum();
            break;
          }
          case 18: {
            if (handshakeInfo_ == null) {
              handshakeInfo_ = new global::Akka.Remote.Serialization.Proto.Msg.AkkaHandshakeInfo();
            }
            input.ReadMessage(handshakeInfo_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class AkkaHandshakeInfo : pb::IMessage<AkkaHandshakeInfo> {
    private static readonly pb::MessageParser<AkkaHandshakeInfo> _parser = new pb::MessageParser<AkkaHandshakeInfo>(() => new AkkaHandshakeInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AkkaHandshakeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Remote.Serialization.Proto.Msg.WireFormatsReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaHandshakeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaHandshakeInfo(AkkaHandshakeInfo other) : this() {
      Origin = other.origin_ != null ? other.Origin.Clone() : null;
      uid_ = other.uid_;
      cookie_ = other.cookie_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AkkaHandshakeInfo Clone() {
      return new AkkaHandshakeInfo(this);
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 1;
    private global::Akka.Remote.Serialization.Proto.Msg.Address origin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Remote.Serialization.Proto.Msg.Address Origin {
      get { return origin_; }
      set {
        origin_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private ulong uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "cookie" field.</summary>
    public const int CookieFieldNumber = 3;
    private string cookie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cookie {
      get { return cookie_; }
      set {
        cookie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AkkaHandshakeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AkkaHandshakeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Origin, other.Origin)) return false;
      if (Uid != other.Uid) return false;
      if (Cookie != other.Cookie) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (origin_ != null) hash ^= Origin.GetHashCode();
      if (Uid != 0UL) hash ^= Uid.GetHashCode();
      if (Cookie.Length != 0) hash ^= Cookie.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (origin_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Origin);
      }
      if (Uid != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(Uid);
      }
      if (Cookie.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cookie);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (origin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Origin);
      }
      if (Uid != 0UL) {
        size += 1 + 8;
      }
      if (Cookie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cookie);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AkkaHandshakeInfo other) {
      if (other == null) {
        return;
      }
      if (other.origin_ != null) {
        if (origin_ == null) {
          origin_ = new global::Akka.Remote.Serialization.Proto.Msg.Address();
        }
        Origin.MergeFrom(other.Origin);
      }
      if (other.Uid != 0UL) {
        Uid = other.Uid;
      }
      if (other.Cookie.Length != 0) {
        Cookie = other.Cookie;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (origin_ == null) {
              origin_ = new global::Akka.Remote.Serialization.Proto.Msg.Address();
            }
            input.ReadMessage(origin_);
            break;
          }
          case 17: {
            Uid = input.ReadFixed64();
            break;
          }
          case 26: {
            Cookie = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
