version: "2.4"

services:
  akka-test:
    image: akka-test
    build: 
      context: .
    cpu_count: 1
    mem_limit: 1g
    environment:
      run_count: 2
      test_file: core/Akka.Remote.Tests/Akka.Remote.Tests.csproj