<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\xunitSettings.props" />
  <PropertyGroup>
    <TargetFrameworks>$(NetFrameworkTestVersion);$(NetTestVersion)</TargetFrameworks>
  </PropertyGroup>
 
  <ItemGroup>
    <ProjectReference Include="..\Akka\Akka.csproj" />
    <ProjectReference Include="..\Akka.Streams\Akka.Streams.csproj" />
    <ProjectReference Include="..\Akka.Streams.TestKit\Akka.Streams.TestKit.csproj" />
    <ProjectReference Include="..\Akka.TestKit\Akka.TestKit.csproj" />
    <ProjectReference Include="..\..\contrib\testkits\Akka.TestKit.Xunit2\Akka.TestKit.Xunit2.csproj" />
    <ProjectReference Include="..\Akka.Tests.Shared.Internals\Akka.Tests.Shared.Internals.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Reactive.Streams.TCK" Version="1.0.4" />
    <!-- !!!WARNING!!! 
         NUNIT VERSION HAVE TO MATCH WITH THE VERSION USED BY REACTIVE TCK. 
         !!!WARNING!!! -->
    <!--<PackageReference Include="NUnit" Version="3.7.1" Condition="'$(TargetFramework)' == '$(NetCoreTestVersion)'"/>-->
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Akka.Streams.Tests.TCK\ActorPublisherTest.cs">
      <Link>ActorPublisherTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\ActorSubscriberTest.cs">
      <Link>ActorSubscriberTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\AkkaIdentityProcessorVerification.cs">
      <Link>AkkaIdentityProcessorVerification.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\AkkaPublisherVerification.cs">
      <Link>AkkaPublisherVerification.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\AkkaSubscriberVerification.cs">
      <Link>AkkaSubscriberVerification.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\ConcatTest.cs">
      <Link>ConcatTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\EmptyPublisherTest.cs">
      <Link>EmptyPublisherTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\FanoutPublisherTest.cs">
      <Link>FanoutPublisherTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\FilePublisherTest.cs">
      <Link>FilePublisherTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\FlattenTest.cs">
      <Link>FlattenTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\FoldSinkSubscriberTest.cs">
      <Link>FoldSinkSubscriberTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\ForeachSinkSubscriberTest.cs">
      <Link>ForeachSinkSubscriberTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\FusableProcessorTest.cs">
      <Link>FusableProcessorTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\GroupByTest.cs">
      <Link>GroupByTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\InputStreamSourceTest.cs">
      <Link>InputStreamSourceTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\IterablePublisherTest.cs">
      <Link>IterablePublisherTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\MaybeSourceTest.cs">
      <Link>MaybeSourceTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\PrefixAndTailTest.cs">
      <Link>PrefixAndTailTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\SelectTest.cs">
      <Link>SelectTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\SingleElementSourceTest.cs">
      <Link>SingleElementSourceTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\SinkholeSubscriberTest.cs">
      <Link>SinkholeSubscriberTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\SplitWhenTest.cs">
      <Link>SplitWhenTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\TaskPublisherTest.cs">
      <Link>TaskPublisherTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\Timeouts.cs">
      <Link>Timeouts.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\TransformProcessorTest.cs">
      <Link>TransformProcessorTest.cs</Link>
    </Compile>
    <Compile Include="..\Akka.Streams.Tests.TCK\VirtualPublisherTest.cs">
      <Link>VirtualPublisherTest.cs</Link>
    </Compile>
  </ItemGroup>

</Project>