<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TestsNetCoreFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Logger.Serilog" Version="1.5.25" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="System.Text.Json" Version="$(SystemTextJsonVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Akka.TestKit.Xunit" Version="$(AkkaVersion)" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageReference Include="Verify.XunitV3" Version="31.14.0" />
    <PackageReference Include="Verify.DiffPlex" Version="3.2.0" />
    <PackageReference Include="xunit.v3" Version="$(Xunit3Version)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(Xunit3RunneVisualstudio)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Hosting.TestKit\Akka.Hosting.TestKit.csproj" />
    <ProjectReference Include="..\Akka.Hosting\Akka.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="test.hocon" />
    <Content Include="test.hocon">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
