<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\xunitSettings.props" />

  <PropertyGroup>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Hosting\Akka.Hosting.csproj" />
    <ProjectReference Include="..\Akka.Hosting.TestKit\Akka.Hosting.TestKit.csproj" />
    <ProjectReference Include="..\..\testkits\Akka.TestKit.Xunit\Akka.TestKit.Xunit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MsExtHostingVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="$(MsExtHostingVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="$(MsExtHostingVersion)" />
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertionsVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageReference Include="Verify.XunitV3" Version="31.14.0" />
    <PackageReference Include="Verify.DiffPlex" Version="3.2.0" />
    <PackageReference Include="xunit.v3" Version="$(Xunit3Version)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(Xunit3RunnerVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="test.hocon" />
    <Content Include="test.hocon">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
