// -----------------------------------------------------------------------
//  <copyright file="HoconSnapshotSpecs.cs" company="Akka.NET Project">
//      Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
//  </copyright>
// -----------------------------------------------------------------------

// The HOCON the Hosting builders emit is part of what Akka.Persistence.Hosting guarantees, so a representative
// set of builder calls has to produce, byte for byte, what it produced before the builders learned to register
// plugins in code. HoconSnapshotSpecs.verified.txt is that text, generated by this file's BuildConfig against the
// Hosting code on akkadotnet/dev. It is the merged configuration the builder holds after the calls, written by
// Config.ToString(includeFallback: true): no key sorting, no whitespace changes.
//
// To regenerate it from dev:
//   1. git archive akkadotnet/dev into a scratch folder.
//   2. Copy this file over src/contrib/hosting/Akka.Persistence.Hosting.Tests/HoconSnapshotSpecs.cs there and put
//      "#define HOCON_BASELINE" on its first line. That drops the typed options dev does not have.
//   3. AKKA_HOCON_SNAPSHOT_OUT=/path/to/HoconSnapshotSpecs.verified.txt dotnet test <that Hosting.Tests project>
//      -c Release --filter HoconSnapshotSpecs
//   4. Copy the file it wrote next to this one.

#nullable enable
using System;
using System.IO;
using System.Linq;
using Akka.Configuration;
using Akka.Hosting;
using Akka.Persistence.Journal;
using Akka.Persistence.Snapshot;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Akka.Persistence.Hosting.Tests;

public class HoconSnapshotSpecs
{
    public sealed class EvtA { }
    public sealed class EvtB { }
    public sealed class EvtC { }

    public sealed class AdapterOne : IEventAdapter
    {
        public string Manifest(object evt) => "one";
        public object ToJournal(object evt) => evt;
        public IEventSequence FromJournal(object evt, string manifest) => EventSequence.Single(evt);
    }

    public sealed class AdapterTwo : IWriteEventAdapter
    {
        public string Manifest(object evt) => "two";
        public object ToJournal(object evt) => evt;
    }

    public sealed class AdapterThree : IReadEventAdapter
    {
        public IEventSequence FromJournal(object evt, string manifest) => EventSequence.Single(evt);
    }

    public sealed class SnapshotJournal : MemoryJournal
    {
    }

    public sealed class SnapshotSnapshotStore : MemorySnapshotStore
    {
    }

    private const string JournalDefaults =
        "class = \"Some.Journal, Some.Assembly\"\nplugin-dispatcher = \"akka.actor.default-dispatcher\"\nconnection-string = none";

    private const string SnapshotDefaults =
        "class = \"Some.SnapshotStore, Some.Assembly\"\nplugin-dispatcher = \"akka.actor.default-dispatcher\"";

    public sealed class SnapshotJournalOptions : JournalOptions
    {
        public SnapshotJournalOptions(string identifier, bool isDefault) : base(isDefault)
        {
            Identifier = identifier;
        }

        public override string Identifier { get; set; }

        protected override Config InternalDefaultConfig => ConfigurationFactory.ParseString(JournalDefaults);
    }

    public sealed class SnapshotSnapshotOptions : SnapshotOptions
    {
        public SnapshotSnapshotOptions(string identifier, bool isDefault) : base(isDefault)
        {
            Identifier = identifier;
        }

        public override string Identifier { get; set; }

        protected override Config InternalDefaultConfig => ConfigurationFactory.ParseString(SnapshotDefaults);
    }

#if !HOCON_BASELINE
    // the same options with the plugin types named in code, which registers them in the setup as well
    public sealed class TypedSnapshotJournalOptions : JournalOptions<SnapshotJournal>
    {
        public TypedSnapshotJournalOptions(string identifier, bool isDefault) : base(isDefault)
        {
            Identifier = identifier;
        }

        public override string Identifier { get; set; }

        protected override Config InternalDefaultConfig => ConfigurationFactory.ParseString(JournalDefaults);
    }

    public sealed class TypedSnapshotSnapshotOptions : SnapshotOptions<SnapshotSnapshotStore>
    {
        public TypedSnapshotSnapshotOptions(string identifier, bool isDefault) : base(isDefault)
        {
            Identifier = identifier;
        }

        public override string Identifier { get; set; }

        protected override Config InternalDefaultConfig => ConfigurationFactory.ParseString(SnapshotDefaults);
    }
#endif

    private static JournalOptions Journal(string identifier, bool isDefault, bool typed)
#if HOCON_BASELINE
        => new SnapshotJournalOptions(identifier, isDefault);
#else
        => typed ? new TypedSnapshotJournalOptions(identifier, isDefault) : new SnapshotJournalOptions(identifier, isDefault);
#endif

    private static SnapshotOptions Snapshot(string identifier, bool isDefault, bool typed)
#if HOCON_BASELINE
        => new SnapshotSnapshotOptions(identifier, isDefault);
#else
        => typed ? new TypedSnapshotSnapshotOptions(identifier, isDefault) : new SnapshotSnapshotOptions(identifier, isDefault);
#endif

    private static string BuildConfig(bool typed)
    {
        var builder = new AkkaConfigurationBuilder(new ServiceCollection(), "hocon-snapshot");

        builder
            .WithJournalAndSnapshot(
                Journal("alpha", true, typed), Snapshot("alpha", true, typed),
                journal => journal
                    .AddEventAdapter<AdapterOne>("one", new[] { typeof(EvtA), typeof(EvtB) })
                    .AddWriteEventAdapter<AdapterTwo>("two", new[] { typeof(EvtB) })
                    .AddReadEventAdapter<AdapterThree>("three", new[] { typeof(EvtC) }),
                snapshot => snapshot.WithHealthCheck())
            .WithJournal(With(Journal("beta", false, typed), j => { j.AutoInitialize = true; j.Serializer = "json"; }))
            .WithSnapshot(With(Snapshot("beta", false, typed), s => s.AutoInitialize = true))
            .WithInMemoryJournal(journal => journal.AddWriteEventAdapter<AdapterTwo>("mem-two", new[] { typeof(EvtA) }), "mem", false)
            .WithInMemoryJournal()
            .WithInMemorySnapshotStore("mem", false)
            .WithInMemorySnapshotStore()
            .WithClusterShardingJournalMigrationAdapter("akka.persistence.journal.alpha")
            .WithClusterShardingJournalMigrationAdapter(Journal("beta", false, typed));
#pragma warning disable CS0618 // the string overload is still part of what Hosting guarantees
        builder.WithJournal("legacy", journal => journal.AddEventAdapter<AdapterOne>("legacy-one", new[] { typeof(EvtC) }));
#pragma warning restore CS0618

        return builder.Configuration.Value.ToString(includeFallback: true);
    }

    private static T With<T>(T options, Action<T> configure)
    {
        configure(options);
        return options;
    }

    [Theory(DisplayName = "The Hosting builders should emit the HOCON they always emitted When a representative set of calls is made")]
    [InlineData(false)]
    [InlineData(true)]
    public void Should_emit_the_HOCON_they_always_emitted_When_a_representative_set_of_calls_is_made(bool typed)
    {
        var actual = BuildConfig(typed);

#if HOCON_BASELINE
        var output = Environment.GetEnvironmentVariable("AKKA_HOCON_SNAPSHOT_OUT");
        if (!string.IsNullOrEmpty(output))
        {
            File.WriteAllText(output, actual);
            return;
        }
#endif

        // Config.ToString writes CRLF on every platform, and git may turn the checked-in file's endings into LF, so
        // the endings are the one thing made equal. Everything else is compared as written.
        // With its types named in code the plugin also registers itself in the setup, and the HOCON must stay what it was.
        ToLf(actual).Should().Be(ToLf(ReadVerified()));
    }

    private static string ToLf(string text) => text.ReplaceLineEndings("\n");

    private static string ReadVerified()
    {
        var assembly = typeof(HoconSnapshotSpecs).Assembly;
        var name = assembly.GetManifestResourceNames().Single(n => n.EndsWith(".HoconSnapshotSpecs.verified.txt", StringComparison.Ordinal));
        using var reader = new StreamReader(assembly.GetManifestResourceStream(name)!);
        return reader.ReadToEnd();
    }
}
