// -----------------------------------------------------------------------
//  <copyright file="HoconSnapshotSpecs.cs" company="Akka.NET Project">
//      Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
//  </copyright>
// -----------------------------------------------------------------------

// The HOCON the Hosting builders emit is part of what Akka.Persistence.Hosting guarantees, so a representative
// set of builder calls has to produce, byte for byte, what it produced before the builders learned to register
// plugins in code. HoconSnapshotSpecs.verified.txt is that text, generated by this file's BuildConfig against the
// Hosting code on akkadotnet/dev. It is the merged configuration the builder holds after the calls, written by
// Config.ToString(includeFallback: true): no key sorting, no whitespace changes.
//
// To regenerate it from dev:
//   1. git archive akkadotnet/dev into a scratch folder.
//   2. Copy this file over src/contrib/hosting/Akka.Persistence.Hosting.Tests/HoconSnapshotSpecs.cs there and put
//      "#define HOCON_BASELINE" on its first line. That drops the one hook dev does not have.
//   3. AKKA_HOCON_SNAPSHOT_OUT=/path/to/HoconSnapshotSpecs.verified.txt dotnet test <that Hosting.Tests project>
//      -c Release --filter HoconSnapshotSpecs
//   4. Copy the file it wrote next to this one.

#nullable enable
using System;
using System.IO;
using System.Linq;
using Akka.Configuration;
using Akka.Hosting;
using Akka.Persistence.Journal;
using Akka.Persistence.Snapshot;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Akka.Persistence.Hosting.Tests;

public class HoconSnapshotSpecs
{
    public sealed class EvtA { }
    public sealed class EvtB { }
    public sealed class EvtC { }

    public sealed class AdapterOne : IEventAdapter
    {
        public string Manifest(object evt) => "one";
        public object ToJournal(object evt) => evt;
        public IEventSequence FromJournal(object evt, string manifest) => EventSequence.Single(evt);
    }

    public sealed class AdapterTwo : IWriteEventAdapter
    {
        public string Manifest(object evt) => "two";
        public object ToJournal(object evt) => evt;
    }

    public sealed class AdapterThree : IReadEventAdapter
    {
        public IEventSequence FromJournal(object evt, string manifest) => EventSequence.Single(evt);
    }

    public sealed class SnapshotJournal : MemoryJournal
    {
    }

    public sealed class SnapshotSnapshotStore : MemorySnapshotStore
    {
    }

    public sealed class SnapshotJournalOptions : JournalOptions
    {
        public SnapshotJournalOptions(string identifier, bool isDefault, bool withFactory) : base(isDefault)
        {
            Identifier = identifier;
            WithFactory = withFactory;
        }

        public bool WithFactory { get; }

        public override string Identifier { get; set; }

        protected override Config InternalDefaultConfig => ConfigurationFactory.ParseString(
            "class = \"Some.Journal, Some.Assembly\"\nplugin-dispatcher = \"akka.actor.default-dispatcher\"\nconnection-string = none");

#if !HOCON_BASELINE
        protected override PluginActorFactory? CreatePluginActorFactory()
            => WithFactory ? PluginActorFactory.For(_ => new SnapshotJournal()) : null;
#endif
    }

    public sealed class SnapshotSnapshotOptions : SnapshotOptions
    {
        public SnapshotSnapshotOptions(string identifier, bool isDefault, bool withFactory) : base(isDefault)
        {
            Identifier = identifier;
            WithFactory = withFactory;
        }

        public bool WithFactory { get; }

        public override string Identifier { get; set; }

        protected override Config InternalDefaultConfig => ConfigurationFactory.ParseString(
            "class = \"Some.SnapshotStore, Some.Assembly\"\nplugin-dispatcher = \"akka.actor.default-dispatcher\"");

#if !HOCON_BASELINE
        protected override PluginActorFactory? CreatePluginActorFactory()
            => WithFactory ? PluginActorFactory.For(_ => new SnapshotSnapshotStore()) : null;
#endif
    }

    private static string BuildConfig(bool withFactory)
    {
        var builder = new AkkaConfigurationBuilder(new ServiceCollection(), "hocon-snapshot");

        builder
            .WithJournalAndSnapshot(
                new SnapshotJournalOptions("alpha", true, withFactory), new SnapshotSnapshotOptions("alpha", true, withFactory),
                journal => journal
                    .AddEventAdapter<AdapterOne>("one", new[] { typeof(EvtA), typeof(EvtB) })
                    .AddWriteEventAdapter<AdapterTwo>("two", new[] { typeof(EvtB) })
                    .AddReadEventAdapter<AdapterThree>("three", new[] { typeof(EvtC) }),
                snapshot => snapshot.WithHealthCheck())
            .WithJournal(new SnapshotJournalOptions("beta", false, withFactory) { AutoInitialize = true, Serializer = "json" })
            .WithSnapshot(new SnapshotSnapshotOptions("beta", false, withFactory) { AutoInitialize = true })
            .WithInMemoryJournal(journal => journal.AddWriteEventAdapter<AdapterTwo>("mem-two", new[] { typeof(EvtA) }), "mem", false)
            .WithInMemoryJournal()
            .WithInMemorySnapshotStore("mem", false)
            .WithInMemorySnapshotStore()
            .WithClusterShardingJournalMigrationAdapter("akka.persistence.journal.alpha")
            .WithClusterShardingJournalMigrationAdapter(new SnapshotJournalOptions("beta", false, withFactory));
#pragma warning disable CS0618 // the string overload is still part of what Hosting guarantees
        builder.WithJournal("legacy", journal => journal.AddEventAdapter<AdapterOne>("legacy-one", new[] { typeof(EvtC) }));
#pragma warning restore CS0618

        return builder.Configuration.Value.ToString(includeFallback: true);
    }

    [Theory(DisplayName = "The Hosting builders should emit the HOCON they always emitted When a representative set of calls is made")]
    [InlineData(false)]
    [InlineData(true)]
    public void Should_emit_the_HOCON_they_always_emitted_When_a_representative_set_of_calls_is_made(bool withFactory)
    {
        var actual = BuildConfig(withFactory);

#if HOCON_BASELINE
        var output = Environment.GetEnvironmentVariable("AKKA_HOCON_SNAPSHOT_OUT");
        if (!string.IsNullOrEmpty(output))
        {
            File.WriteAllText(output, actual);
            return;
        }
#endif

        // Config.ToString writes CRLF on every platform, and git may turn the checked-in file's endings into LF, so
        // the endings are the one thing made equal. Everything else is compared as written.
        // With a factory the plugin also registers itself in code, and the HOCON must stay what it was.
        ToLf(actual).Should().Be(ToLf(ReadVerified()));
    }

    private static string ToLf(string text) => text.ReplaceLineEndings("\n");

    private static string ReadVerified()
    {
        var assembly = typeof(HoconSnapshotSpecs).Assembly;
        var name = assembly.GetManifestResourceNames().Single(n => n.EndsWith(".HoconSnapshotSpecs.verified.txt", StringComparison.Ordinal));
        using var reader = new StreamReader(assembly.GetManifestResourceStream(name)!);
        return reader.ReadToEnd();
    }
}
