// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ReliableDelivery.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akka.Cluster.Sharding.Serialization.Proto.Msg {

  /// <summary>Holder for reflection information generated from ReliableDelivery.proto</summary>
  internal static partial class ReliableDeliveryReflection {

    #region Descriptor
    /// <summary>File descriptor for ReliableDelivery.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReliableDeliveryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZSZWxpYWJsZURlbGl2ZXJ5LnByb3RvEi1Ba2thLkNsdXN0ZXIuU2hhcmRp",
            "bmcuU2VyaWFsaXphdGlvbi5Qcm90by5Nc2caFkNvbnRhaW5lckZvcm1hdHMu",
            "cHJvdG8i/QEKEFNlcXVlbmNlZE1lc3NhZ2USEgoKcHJvZHVjZXJJZBgBIAEo",
            "CRINCgVzZXFOchgCIAEoAxINCgVmaXJzdBgDIAEoCBILCgNhY2sYBCABKAgS",
            "HQoVcHJvZHVjZXJDb250cm9sbGVyUmVmGAUgASgJEj0KB21lc3NhZ2UYBiAB",
            "KAsyLC5Ba2thLlJlbW90ZS5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5QYXls",
            "b2FkEhcKCmZpcnN0Q2h1bmsYByABKAhIAIgBARIWCglsYXN0Q2h1bmsYCCAB",
            "KAhIAYgBAUINCgtfZmlyc3RDaHVua0IMCgpfbGFzdENodW5rIjEKEFJlZ2lz",
            "dGVyQ29uc3VtZXISHQoVY29uc3VtZXJDb250cm9sbGVyUmVmGAEgASgJImYK",
            "B1JlcXVlc3QSFgoOY29uZmlybWVkU2VxTnIYASABKAMSGAoQcmVxdWVzdFVw",
            "VG9TZXFOchgCIAEoAxIVCg1zdXBwb3J0UmVzZW5kGAMgASgIEhIKCnZpYVRp",
            "bWVvdXQYBCABKAgiGwoGUmVzZW5kEhEKCWZyb21TZXFOchgBIAEoAyIdCgNB",
            "Y2sSFgoOY29uZmlybWVkU2VxTnIYASABKAMi2gEKBVN0YXRlEhQKDGN1cnJl",
            "bnRTZXFOchgBIAEoAxIdChVoaWdoZXN0Q29uZmlybWVkU2VxTnIYAiABKAMS",
            "SwoJY29uZmlybWVkGAMgAygLMjguQWtrYS5DbHVzdGVyLlNoYXJkaW5nLlNl",
            "cmlhbGl6YXRpb24uUHJvdG8uTXNnLkNvbmZpcm1lZBJPCgt1bmNvbmZpcm1l",
            "ZBgEIAMoCzI6LkFra2EuQ2x1c3Rlci5TaGFyZGluZy5TZXJpYWxpemF0aW9u",
            "LlByb3RvLk1zZy5NZXNzYWdlU2VudCJACglDb25maXJtZWQSDQoFc2VxTnIY",
            "ASABKAMSEQoJcXVhbGlmaWVyGAIgASgJEhEKCXRpbWVzdGFtcBgDIAEoAyLc",
            "AQoLTWVzc2FnZVNlbnQSDQoFc2VxTnIYASABKAMSEQoJcXVhbGlmaWVyGAIg",
            "ASgJEgsKA2FjaxgDIAEoCBIRCgl0aW1lc3RhbXAYBCABKAMSPQoHbWVzc2Fn",
            "ZRgFIAEoCzIsLkFra2EuUmVtb3RlLlNlcmlhbGl6YXRpb24uUHJvdG8uTXNn",
            "LlBheWxvYWQSFwoKZmlyc3RDaHVuaxgGIAEoCEgAiAEBEhYKCWxhc3RDaHVu",
            "axgHIAEoCEgBiAEBQg0KC19maXJzdENodW5rQgwKCl9sYXN0Q2h1bmsiHQoH",
            "Q2xlYW51cBISCgpxdWFsaWZpZXJzGAEgAygJQgJIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Akka.Remote.Serialization.Proto.Msg.ContainerFormatsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.SequencedMessage), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.SequencedMessage.Parser, new[]{ "ProducerId", "SeqNr", "First", "Ack", "ProducerControllerRef", "Message", "FirstChunk", "LastChunk" }, new[]{ "FirstChunk", "LastChunk" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.RegisterConsumer), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.RegisterConsumer.Parser, new[]{ "ConsumerControllerRef" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Request), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Request.Parser, new[]{ "ConfirmedSeqNr", "RequestUpToSeqNr", "SupportResend", "ViaTimeout" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Resend), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Resend.Parser, new[]{ "FromSeqNr" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Ack), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Ack.Parser, new[]{ "ConfirmedSeqNr" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.State), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.State.Parser, new[]{ "CurrentSeqNr", "HighestConfirmedSeqNr", "Confirmed", "Unconfirmed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed.Parser, new[]{ "SeqNr", "Qualifier", "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent.Parser, new[]{ "SeqNr", "Qualifier", "Ack", "Timestamp", "Message", "FirstChunk", "LastChunk" }, new[]{ "FirstChunk", "LastChunk" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Cleanup), global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Cleanup.Parser, new[]{ "Qualifiers" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// ConsumerController
  /// </summary>
  internal sealed partial class SequencedMessage : pb::IMessage<SequencedMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SequencedMessage> _parser = new pb::MessageParser<SequencedMessage>(() => new SequencedMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SequencedMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequencedMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequencedMessage(SequencedMessage other) : this() {
      _hasBits0 = other._hasBits0;
      producerId_ = other.producerId_;
      seqNr_ = other.seqNr_;
      first_ = other.first_;
      ack_ = other.ack_;
      producerControllerRef_ = other.producerControllerRef_;
      message_ = other.message_ != null ? other.message_.Clone() : null;
      firstChunk_ = other.firstChunk_;
      lastChunk_ = other.lastChunk_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequencedMessage Clone() {
      return new SequencedMessage(this);
    }

    /// <summary>Field number for the "producerId" field.</summary>
    public const int ProducerIdFieldNumber = 1;
    private string producerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProducerId {
      get { return producerId_; }
      set {
        producerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "seqNr" field.</summary>
    public const int SeqNrFieldNumber = 2;
    private long seqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SeqNr {
      get { return seqNr_; }
      set {
        seqNr_ = value;
      }
    }

    /// <summary>Field number for the "first" field.</summary>
    public const int FirstFieldNumber = 3;
    private bool first_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool First {
      get { return first_; }
      set {
        first_ = value;
      }
    }

    /// <summary>Field number for the "ack" field.</summary>
    public const int AckFieldNumber = 4;
    private bool ack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ack {
      get { return ack_; }
      set {
        ack_ = value;
      }
    }

    /// <summary>Field number for the "producerControllerRef" field.</summary>
    public const int ProducerControllerRefFieldNumber = 5;
    private string producerControllerRef_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProducerControllerRef {
      get { return producerControllerRef_; }
      set {
        producerControllerRef_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 6;
    private global::Akka.Remote.Serialization.Proto.Msg.Payload message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Akka.Remote.Serialization.Proto.Msg.Payload Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    /// <summary>Field number for the "firstChunk" field.</summary>
    public const int FirstChunkFieldNumber = 7;
    private bool firstChunk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FirstChunk {
      get { if ((_hasBits0 & 1) != 0) { return firstChunk_; } else { return false; } }
      set {
        _hasBits0 |= 1;
        firstChunk_ = value;
      }
    }
    /// <summary>Gets whether the "firstChunk" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFirstChunk {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "firstChunk" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFirstChunk() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "lastChunk" field.</summary>
    public const int LastChunkFieldNumber = 8;
    private bool lastChunk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LastChunk {
      get { if ((_hasBits0 & 2) != 0) { return lastChunk_; } else { return false; } }
      set {
        _hasBits0 |= 2;
        lastChunk_ = value;
      }
    }
    /// <summary>Gets whether the "lastChunk" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLastChunk {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "lastChunk" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLastChunk() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SequencedMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SequencedMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProducerId != other.ProducerId) return false;
      if (SeqNr != other.SeqNr) return false;
      if (First != other.First) return false;
      if (Ack != other.Ack) return false;
      if (ProducerControllerRef != other.ProducerControllerRef) return false;
      if (!object.Equals(Message, other.Message)) return false;
      if (FirstChunk != other.FirstChunk) return false;
      if (LastChunk != other.LastChunk) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProducerId.Length != 0) hash ^= ProducerId.GetHashCode();
      if (SeqNr != 0L) hash ^= SeqNr.GetHashCode();
      if (First != false) hash ^= First.GetHashCode();
      if (Ack != false) hash ^= Ack.GetHashCode();
      if (ProducerControllerRef.Length != 0) hash ^= ProducerControllerRef.GetHashCode();
      if (message_ != null) hash ^= Message.GetHashCode();
      if (HasFirstChunk) hash ^= FirstChunk.GetHashCode();
      if (HasLastChunk) hash ^= LastChunk.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProducerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProducerId);
      }
      if (SeqNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SeqNr);
      }
      if (First != false) {
        output.WriteRawTag(24);
        output.WriteBool(First);
      }
      if (Ack != false) {
        output.WriteRawTag(32);
        output.WriteBool(Ack);
      }
      if (ProducerControllerRef.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProducerControllerRef);
      }
      if (message_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Message);
      }
      if (HasFirstChunk) {
        output.WriteRawTag(56);
        output.WriteBool(FirstChunk);
      }
      if (HasLastChunk) {
        output.WriteRawTag(64);
        output.WriteBool(LastChunk);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProducerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProducerId);
      }
      if (SeqNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SeqNr);
      }
      if (First != false) {
        output.WriteRawTag(24);
        output.WriteBool(First);
      }
      if (Ack != false) {
        output.WriteRawTag(32);
        output.WriteBool(Ack);
      }
      if (ProducerControllerRef.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProducerControllerRef);
      }
      if (message_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Message);
      }
      if (HasFirstChunk) {
        output.WriteRawTag(56);
        output.WriteBool(FirstChunk);
      }
      if (HasLastChunk) {
        output.WriteRawTag(64);
        output.WriteBool(LastChunk);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProducerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProducerId);
      }
      if (SeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SeqNr);
      }
      if (First != false) {
        size += 1 + 1;
      }
      if (Ack != false) {
        size += 1 + 1;
      }
      if (ProducerControllerRef.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProducerControllerRef);
      }
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (HasFirstChunk) {
        size += 1 + 1;
      }
      if (HasLastChunk) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SequencedMessage other) {
      if (other == null) {
        return;
      }
      if (other.ProducerId.Length != 0) {
        ProducerId = other.ProducerId;
      }
      if (other.SeqNr != 0L) {
        SeqNr = other.SeqNr;
      }
      if (other.First != false) {
        First = other.First;
      }
      if (other.Ack != false) {
        Ack = other.Ack;
      }
      if (other.ProducerControllerRef.Length != 0) {
        ProducerControllerRef = other.ProducerControllerRef;
      }
      if (other.message_ != null) {
        if (message_ == null) {
          Message = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
        }
        Message.MergeFrom(other.Message);
      }
      if (other.HasFirstChunk) {
        FirstChunk = other.FirstChunk;
      }
      if (other.HasLastChunk) {
        LastChunk = other.LastChunk;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ProducerId = input.ReadString();
            break;
          }
          case 16: {
            SeqNr = input.ReadInt64();
            break;
          }
          case 24: {
            First = input.ReadBool();
            break;
          }
          case 32: {
            Ack = input.ReadBool();
            break;
          }
          case 42: {
            ProducerControllerRef = input.ReadString();
            break;
          }
          case 50: {
            if (message_ == null) {
              Message = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
            }
            input.ReadMessage(Message);
            break;
          }
          case 56: {
            FirstChunk = input.ReadBool();
            break;
          }
          case 64: {
            LastChunk = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ProducerId = input.ReadString();
            break;
          }
          case 16: {
            SeqNr = input.ReadInt64();
            break;
          }
          case 24: {
            First = input.ReadBool();
            break;
          }
          case 32: {
            Ack = input.ReadBool();
            break;
          }
          case 42: {
            ProducerControllerRef = input.ReadString();
            break;
          }
          case 50: {
            if (message_ == null) {
              Message = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
            }
            input.ReadMessage(Message);
            break;
          }
          case 56: {
            FirstChunk = input.ReadBool();
            break;
          }
          case 64: {
            LastChunk = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ProducerController
  /// </summary>
  internal sealed partial class RegisterConsumer : pb::IMessage<RegisterConsumer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterConsumer> _parser = new pb::MessageParser<RegisterConsumer>(() => new RegisterConsumer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterConsumer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterConsumer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterConsumer(RegisterConsumer other) : this() {
      consumerControllerRef_ = other.consumerControllerRef_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterConsumer Clone() {
      return new RegisterConsumer(this);
    }

    /// <summary>Field number for the "consumerControllerRef" field.</summary>
    public const int ConsumerControllerRefFieldNumber = 1;
    private string consumerControllerRef_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConsumerControllerRef {
      get { return consumerControllerRef_; }
      set {
        consumerControllerRef_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterConsumer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterConsumer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConsumerControllerRef != other.ConsumerControllerRef) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ConsumerControllerRef.Length != 0) hash ^= ConsumerControllerRef.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ConsumerControllerRef.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ConsumerControllerRef);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ConsumerControllerRef.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ConsumerControllerRef);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ConsumerControllerRef.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConsumerControllerRef);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterConsumer other) {
      if (other == null) {
        return;
      }
      if (other.ConsumerControllerRef.Length != 0) {
        ConsumerControllerRef = other.ConsumerControllerRef;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ConsumerControllerRef = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ConsumerControllerRef = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ProducerController
  /// </summary>
  internal sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      confirmedSeqNr_ = other.confirmedSeqNr_;
      requestUpToSeqNr_ = other.requestUpToSeqNr_;
      supportResend_ = other.supportResend_;
      viaTimeout_ = other.viaTimeout_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "confirmedSeqNr" field.</summary>
    public const int ConfirmedSeqNrFieldNumber = 1;
    private long confirmedSeqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ConfirmedSeqNr {
      get { return confirmedSeqNr_; }
      set {
        confirmedSeqNr_ = value;
      }
    }

    /// <summary>Field number for the "requestUpToSeqNr" field.</summary>
    public const int RequestUpToSeqNrFieldNumber = 2;
    private long requestUpToSeqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RequestUpToSeqNr {
      get { return requestUpToSeqNr_; }
      set {
        requestUpToSeqNr_ = value;
      }
    }

    /// <summary>Field number for the "supportResend" field.</summary>
    public const int SupportResendFieldNumber = 3;
    private bool supportResend_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SupportResend {
      get { return supportResend_; }
      set {
        supportResend_ = value;
      }
    }

    /// <summary>Field number for the "viaTimeout" field.</summary>
    public const int ViaTimeoutFieldNumber = 4;
    private bool viaTimeout_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ViaTimeout {
      get { return viaTimeout_; }
      set {
        viaTimeout_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfirmedSeqNr != other.ConfirmedSeqNr) return false;
      if (RequestUpToSeqNr != other.RequestUpToSeqNr) return false;
      if (SupportResend != other.SupportResend) return false;
      if (ViaTimeout != other.ViaTimeout) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfirmedSeqNr != 0L) hash ^= ConfirmedSeqNr.GetHashCode();
      if (RequestUpToSeqNr != 0L) hash ^= RequestUpToSeqNr.GetHashCode();
      if (SupportResend != false) hash ^= SupportResend.GetHashCode();
      if (ViaTimeout != false) hash ^= ViaTimeout.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ConfirmedSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ConfirmedSeqNr);
      }
      if (RequestUpToSeqNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(RequestUpToSeqNr);
      }
      if (SupportResend != false) {
        output.WriteRawTag(24);
        output.WriteBool(SupportResend);
      }
      if (ViaTimeout != false) {
        output.WriteRawTag(32);
        output.WriteBool(ViaTimeout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ConfirmedSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ConfirmedSeqNr);
      }
      if (RequestUpToSeqNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(RequestUpToSeqNr);
      }
      if (SupportResend != false) {
        output.WriteRawTag(24);
        output.WriteBool(SupportResend);
      }
      if (ViaTimeout != false) {
        output.WriteRawTag(32);
        output.WriteBool(ViaTimeout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ConfirmedSeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ConfirmedSeqNr);
      }
      if (RequestUpToSeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RequestUpToSeqNr);
      }
      if (SupportResend != false) {
        size += 1 + 1;
      }
      if (ViaTimeout != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.ConfirmedSeqNr != 0L) {
        ConfirmedSeqNr = other.ConfirmedSeqNr;
      }
      if (other.RequestUpToSeqNr != 0L) {
        RequestUpToSeqNr = other.RequestUpToSeqNr;
      }
      if (other.SupportResend != false) {
        SupportResend = other.SupportResend;
      }
      if (other.ViaTimeout != false) {
        ViaTimeout = other.ViaTimeout;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfirmedSeqNr = input.ReadInt64();
            break;
          }
          case 16: {
            RequestUpToSeqNr = input.ReadInt64();
            break;
          }
          case 24: {
            SupportResend = input.ReadBool();
            break;
          }
          case 32: {
            ViaTimeout = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ConfirmedSeqNr = input.ReadInt64();
            break;
          }
          case 16: {
            RequestUpToSeqNr = input.ReadInt64();
            break;
          }
          case 24: {
            SupportResend = input.ReadBool();
            break;
          }
          case 32: {
            ViaTimeout = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ProducerController
  /// </summary>
  internal sealed partial class Resend : pb::IMessage<Resend>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Resend> _parser = new pb::MessageParser<Resend>(() => new Resend());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Resend> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Resend() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Resend(Resend other) : this() {
      fromSeqNr_ = other.fromSeqNr_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Resend Clone() {
      return new Resend(this);
    }

    /// <summary>Field number for the "fromSeqNr" field.</summary>
    public const int FromSeqNrFieldNumber = 1;
    private long fromSeqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FromSeqNr {
      get { return fromSeqNr_; }
      set {
        fromSeqNr_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Resend);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Resend other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromSeqNr != other.FromSeqNr) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FromSeqNr != 0L) hash ^= FromSeqNr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FromSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FromSeqNr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FromSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FromSeqNr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FromSeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FromSeqNr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Resend other) {
      if (other == null) {
        return;
      }
      if (other.FromSeqNr != 0L) {
        FromSeqNr = other.FromSeqNr;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FromSeqNr = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FromSeqNr = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ProducerController
  /// </summary>
  internal sealed partial class Ack : pb::IMessage<Ack>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ack> _parser = new pb::MessageParser<Ack>(() => new Ack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ack(Ack other) : this() {
      confirmedSeqNr_ = other.confirmedSeqNr_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ack Clone() {
      return new Ack(this);
    }

    /// <summary>Field number for the "confirmedSeqNr" field.</summary>
    public const int ConfirmedSeqNrFieldNumber = 1;
    private long confirmedSeqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ConfirmedSeqNr {
      get { return confirmedSeqNr_; }
      set {
        confirmedSeqNr_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfirmedSeqNr != other.ConfirmedSeqNr) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfirmedSeqNr != 0L) hash ^= ConfirmedSeqNr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ConfirmedSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ConfirmedSeqNr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ConfirmedSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ConfirmedSeqNr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ConfirmedSeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ConfirmedSeqNr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ack other) {
      if (other == null) {
        return;
      }
      if (other.ConfirmedSeqNr != 0L) {
        ConfirmedSeqNr = other.ConfirmedSeqNr;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfirmedSeqNr = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ConfirmedSeqNr = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DurableProducerQueue
  /// </summary>
  internal sealed partial class State : pb::IMessage<State>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<State> _parser = new pb::MessageParser<State>(() => new State());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<State> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public State() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public State(State other) : this() {
      currentSeqNr_ = other.currentSeqNr_;
      highestConfirmedSeqNr_ = other.highestConfirmedSeqNr_;
      confirmed_ = other.confirmed_.Clone();
      unconfirmed_ = other.unconfirmed_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public State Clone() {
      return new State(this);
    }

    /// <summary>Field number for the "currentSeqNr" field.</summary>
    public const int CurrentSeqNrFieldNumber = 1;
    private long currentSeqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CurrentSeqNr {
      get { return currentSeqNr_; }
      set {
        currentSeqNr_ = value;
      }
    }

    /// <summary>Field number for the "highestConfirmedSeqNr" field.</summary>
    public const int HighestConfirmedSeqNrFieldNumber = 2;
    private long highestConfirmedSeqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HighestConfirmedSeqNr {
      get { return highestConfirmedSeqNr_; }
      set {
        highestConfirmedSeqNr_ = value;
      }
    }

    /// <summary>Field number for the "confirmed" field.</summary>
    public const int ConfirmedFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed> _repeated_confirmed_codec
        = pb::FieldCodec.ForMessage(26, global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed> confirmed_ = new pbc::RepeatedField<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.Confirmed> Confirmed {
      get { return confirmed_; }
    }

    /// <summary>Field number for the "unconfirmed" field.</summary>
    public const int UnconfirmedFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent> _repeated_unconfirmed_codec
        = pb::FieldCodec.ForMessage(34, global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent> unconfirmed_ = new pbc::RepeatedField<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Akka.Cluster.Sharding.Serialization.Proto.Msg.MessageSent> Unconfirmed {
      get { return unconfirmed_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as State);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(State other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentSeqNr != other.CurrentSeqNr) return false;
      if (HighestConfirmedSeqNr != other.HighestConfirmedSeqNr) return false;
      if(!confirmed_.Equals(other.confirmed_)) return false;
      if(!unconfirmed_.Equals(other.unconfirmed_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentSeqNr != 0L) hash ^= CurrentSeqNr.GetHashCode();
      if (HighestConfirmedSeqNr != 0L) hash ^= HighestConfirmedSeqNr.GetHashCode();
      hash ^= confirmed_.GetHashCode();
      hash ^= unconfirmed_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CurrentSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CurrentSeqNr);
      }
      if (HighestConfirmedSeqNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(HighestConfirmedSeqNr);
      }
      confirmed_.WriteTo(output, _repeated_confirmed_codec);
      unconfirmed_.WriteTo(output, _repeated_unconfirmed_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CurrentSeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CurrentSeqNr);
      }
      if (HighestConfirmedSeqNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(HighestConfirmedSeqNr);
      }
      confirmed_.WriteTo(ref output, _repeated_confirmed_codec);
      unconfirmed_.WriteTo(ref output, _repeated_unconfirmed_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurrentSeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CurrentSeqNr);
      }
      if (HighestConfirmedSeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HighestConfirmedSeqNr);
      }
      size += confirmed_.CalculateSize(_repeated_confirmed_codec);
      size += unconfirmed_.CalculateSize(_repeated_unconfirmed_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(State other) {
      if (other == null) {
        return;
      }
      if (other.CurrentSeqNr != 0L) {
        CurrentSeqNr = other.CurrentSeqNr;
      }
      if (other.HighestConfirmedSeqNr != 0L) {
        HighestConfirmedSeqNr = other.HighestConfirmedSeqNr;
      }
      confirmed_.Add(other.confirmed_);
      unconfirmed_.Add(other.unconfirmed_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CurrentSeqNr = input.ReadInt64();
            break;
          }
          case 16: {
            HighestConfirmedSeqNr = input.ReadInt64();
            break;
          }
          case 26: {
            confirmed_.AddEntriesFrom(input, _repeated_confirmed_codec);
            break;
          }
          case 34: {
            unconfirmed_.AddEntriesFrom(input, _repeated_unconfirmed_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CurrentSeqNr = input.ReadInt64();
            break;
          }
          case 16: {
            HighestConfirmedSeqNr = input.ReadInt64();
            break;
          }
          case 26: {
            confirmed_.AddEntriesFrom(ref input, _repeated_confirmed_codec);
            break;
          }
          case 34: {
            unconfirmed_.AddEntriesFrom(ref input, _repeated_unconfirmed_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DurableProducerQueue
  /// </summary>
  internal sealed partial class Confirmed : pb::IMessage<Confirmed>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Confirmed> _parser = new pb::MessageParser<Confirmed>(() => new Confirmed());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Confirmed> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Confirmed() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Confirmed(Confirmed other) : this() {
      seqNr_ = other.seqNr_;
      qualifier_ = other.qualifier_;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Confirmed Clone() {
      return new Confirmed(this);
    }

    /// <summary>Field number for the "seqNr" field.</summary>
    public const int SeqNrFieldNumber = 1;
    private long seqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SeqNr {
      get { return seqNr_; }
      set {
        seqNr_ = value;
      }
    }

    /// <summary>Field number for the "qualifier" field.</summary>
    public const int QualifierFieldNumber = 2;
    private string qualifier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Qualifier {
      get { return qualifier_; }
      set {
        qualifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Confirmed);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Confirmed other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeqNr != other.SeqNr) return false;
      if (Qualifier != other.Qualifier) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeqNr != 0L) hash ^= SeqNr.GetHashCode();
      if (Qualifier.Length != 0) hash ^= Qualifier.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SeqNr);
      }
      if (Qualifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Qualifier);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SeqNr);
      }
      if (Qualifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Qualifier);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SeqNr);
      }
      if (Qualifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Qualifier);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Confirmed other) {
      if (other == null) {
        return;
      }
      if (other.SeqNr != 0L) {
        SeqNr = other.SeqNr;
      }
      if (other.Qualifier.Length != 0) {
        Qualifier = other.Qualifier;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeqNr = input.ReadInt64();
            break;
          }
          case 18: {
            Qualifier = input.ReadString();
            break;
          }
          case 24: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeqNr = input.ReadInt64();
            break;
          }
          case 18: {
            Qualifier = input.ReadString();
            break;
          }
          case 24: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DurableProducerQueue
  /// </summary>
  internal sealed partial class MessageSent : pb::IMessage<MessageSent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageSent> _parser = new pb::MessageParser<MessageSent>(() => new MessageSent());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageSent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSent(MessageSent other) : this() {
      _hasBits0 = other._hasBits0;
      seqNr_ = other.seqNr_;
      qualifier_ = other.qualifier_;
      ack_ = other.ack_;
      timestamp_ = other.timestamp_;
      message_ = other.message_ != null ? other.message_.Clone() : null;
      firstChunk_ = other.firstChunk_;
      lastChunk_ = other.lastChunk_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageSent Clone() {
      return new MessageSent(this);
    }

    /// <summary>Field number for the "seqNr" field.</summary>
    public const int SeqNrFieldNumber = 1;
    private long seqNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SeqNr {
      get { return seqNr_; }
      set {
        seqNr_ = value;
      }
    }

    /// <summary>Field number for the "qualifier" field.</summary>
    public const int QualifierFieldNumber = 2;
    private string qualifier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Qualifier {
      get { return qualifier_; }
      set {
        qualifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ack" field.</summary>
    public const int AckFieldNumber = 3;
    private bool ack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ack {
      get { return ack_; }
      set {
        ack_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 4;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 5;
    private global::Akka.Remote.Serialization.Proto.Msg.Payload message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Akka.Remote.Serialization.Proto.Msg.Payload Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    /// <summary>Field number for the "firstChunk" field.</summary>
    public const int FirstChunkFieldNumber = 6;
    private bool firstChunk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FirstChunk {
      get { if ((_hasBits0 & 1) != 0) { return firstChunk_; } else { return false; } }
      set {
        _hasBits0 |= 1;
        firstChunk_ = value;
      }
    }
    /// <summary>Gets whether the "firstChunk" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFirstChunk {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "firstChunk" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFirstChunk() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "lastChunk" field.</summary>
    public const int LastChunkFieldNumber = 7;
    private bool lastChunk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LastChunk {
      get { if ((_hasBits0 & 2) != 0) { return lastChunk_; } else { return false; } }
      set {
        _hasBits0 |= 2;
        lastChunk_ = value;
      }
    }
    /// <summary>Gets whether the "lastChunk" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLastChunk {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "lastChunk" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLastChunk() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageSent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageSent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeqNr != other.SeqNr) return false;
      if (Qualifier != other.Qualifier) return false;
      if (Ack != other.Ack) return false;
      if (Timestamp != other.Timestamp) return false;
      if (!object.Equals(Message, other.Message)) return false;
      if (FirstChunk != other.FirstChunk) return false;
      if (LastChunk != other.LastChunk) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeqNr != 0L) hash ^= SeqNr.GetHashCode();
      if (Qualifier.Length != 0) hash ^= Qualifier.GetHashCode();
      if (Ack != false) hash ^= Ack.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (message_ != null) hash ^= Message.GetHashCode();
      if (HasFirstChunk) hash ^= FirstChunk.GetHashCode();
      if (HasLastChunk) hash ^= LastChunk.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SeqNr);
      }
      if (Qualifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Qualifier);
      }
      if (Ack != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ack);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Timestamp);
      }
      if (message_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Message);
      }
      if (HasFirstChunk) {
        output.WriteRawTag(48);
        output.WriteBool(FirstChunk);
      }
      if (HasLastChunk) {
        output.WriteRawTag(56);
        output.WriteBool(LastChunk);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeqNr != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SeqNr);
      }
      if (Qualifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Qualifier);
      }
      if (Ack != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ack);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Timestamp);
      }
      if (message_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Message);
      }
      if (HasFirstChunk) {
        output.WriteRawTag(48);
        output.WriteBool(FirstChunk);
      }
      if (HasLastChunk) {
        output.WriteRawTag(56);
        output.WriteBool(LastChunk);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeqNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SeqNr);
      }
      if (Qualifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Qualifier);
      }
      if (Ack != false) {
        size += 1 + 1;
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (HasFirstChunk) {
        size += 1 + 1;
      }
      if (HasLastChunk) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageSent other) {
      if (other == null) {
        return;
      }
      if (other.SeqNr != 0L) {
        SeqNr = other.SeqNr;
      }
      if (other.Qualifier.Length != 0) {
        Qualifier = other.Qualifier;
      }
      if (other.Ack != false) {
        Ack = other.Ack;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.message_ != null) {
        if (message_ == null) {
          Message = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
        }
        Message.MergeFrom(other.Message);
      }
      if (other.HasFirstChunk) {
        FirstChunk = other.FirstChunk;
      }
      if (other.HasLastChunk) {
        LastChunk = other.LastChunk;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeqNr = input.ReadInt64();
            break;
          }
          case 18: {
            Qualifier = input.ReadString();
            break;
          }
          case 24: {
            Ack = input.ReadBool();
            break;
          }
          case 32: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 42: {
            if (message_ == null) {
              Message = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
            }
            input.ReadMessage(Message);
            break;
          }
          case 48: {
            FirstChunk = input.ReadBool();
            break;
          }
          case 56: {
            LastChunk = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeqNr = input.ReadInt64();
            break;
          }
          case 18: {
            Qualifier = input.ReadString();
            break;
          }
          case 24: {
            Ack = input.ReadBool();
            break;
          }
          case 32: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 42: {
            if (message_ == null) {
              Message = new global::Akka.Remote.Serialization.Proto.Msg.Payload();
            }
            input.ReadMessage(Message);
            break;
          }
          case 48: {
            FirstChunk = input.ReadBool();
            break;
          }
          case 56: {
            LastChunk = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// DurableProducerQueue
  /// </summary>
  internal sealed partial class Cleanup : pb::IMessage<Cleanup>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cleanup> _parser = new pb::MessageParser<Cleanup>(() => new Cleanup());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cleanup> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Sharding.Serialization.Proto.Msg.ReliableDeliveryReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cleanup() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cleanup(Cleanup other) : this() {
      qualifiers_ = other.qualifiers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cleanup Clone() {
      return new Cleanup(this);
    }

    /// <summary>Field number for the "qualifiers" field.</summary>
    public const int QualifiersFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_qualifiers_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> qualifiers_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Qualifiers {
      get { return qualifiers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cleanup);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cleanup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!qualifiers_.Equals(other.qualifiers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= qualifiers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      qualifiers_.WriteTo(output, _repeated_qualifiers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      qualifiers_.WriteTo(ref output, _repeated_qualifiers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += qualifiers_.CalculateSize(_repeated_qualifiers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cleanup other) {
      if (other == null) {
        return;
      }
      qualifiers_.Add(other.qualifiers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            qualifiers_.AddEntriesFrom(input, _repeated_qualifiers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            qualifiers_.AddEntriesFrom(ref input, _repeated_qualifiers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
