<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>TestKit for writing tests for Akka.NET using Akka.Hosting and xUnit.</Description>
        <TargetFrameworks>$(LibraryFramework);$(NetLibraryFramework)</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka.TestKit.Xunit" Version="$(AkkaVersion)" />
        <PackageReference Include="Akka.Persistence.TestKit" Version="$(AkkaVersion)" />
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="xunit.v3.extensibility.core" Version="$(Xunit3Version)" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="System.Text.Json" Version="$(SystemTextJsonVersion)" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Akka.Hosting\Akka.Hosting.csproj" />
      <ProjectReference Include="..\Akka.Persistence.Hosting\Akka.Persistence.Hosting.csproj" />
    </ItemGroup>

</Project>
