# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: windows-2019 # Windows Server 2019 with Visual Studio 2019
  demands: Cmd

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - dev

variables:
  - group: nugetKeys #create this group with SECRET variables `nugetKey`

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 5.0.101'
  inputs:
    packageType: sdk
    version: 5.0.101
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.105'
  inputs:
    packageType: sdk
    version: 3.1.105
- task: BatchScript@1
  displayName: 'FAKE Build'
  inputs:
    filename: build.cmd
    arguments: 'Nuget nugetprerelease=dev nugetpublishurl=$(nightlyUrl) nugetkey=$(nightlyKey)'