# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: windows-latest

trigger:
  branches:
    include:
      - refs/tags/*

pr: none

variables:
  - group: signingSecrets #create this group with SECRET variables `signingUsername` and `signingPassword`
  - group: nugetKeys #create this group with SECRET variables `nugetKey`
  - name: githubConnectionName
    value: AkkaDotNet_Releases
  - name: projectName
    value: akka.net
  - name: githubRepositoryName
    value: akkadotnet/akka.net
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK from global.json'
    inputs:
      useGlobalJson: true
      
  - powershell: ./build.ps1
    displayName: 'Update Release Notes'

  # Pack without version suffix for release
  - script: dotnet pack -c Release -o $(Build.ArtifactStagingDirectory)/nuget
    displayName: 'Create packages'

  - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)\nuget\*.nupkg" --api-key $(nugetKey) --source https://api.nuget.org/v3/index.json --skip-duplicate
    displayName: 'Publish to NuGet.org'

  - powershell: |
      $content = Get-Content RELEASE_NOTES.md -Raw
      if ($content -match '(?s)(####.+?)(?=\n####|\z)') {
        $Matches[1].Trim() | Set-Content RELEASE_NOTES_LATEST.md
      } else {
        $content | Set-Content RELEASE_NOTES_LATEST.md
      }
    displayName: 'Extract latest release notes'

  - task: GitHubRelease@0
    displayName: 'GitHub release (create)'
    inputs:
      gitHubConnection: $(githubConnectionName)
      repositoryName: $(githubRepositoryName)
      title: '$(projectName) v$(Build.SourceBranchName)'
      releaseNotesFile: 'RELEASE_NOTES_LATEST.md'
      assets: |
        $(Build.ArtifactStagingDirectory)/nuget/*.nupkg
