<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <Description>Akka.Remote x-plat performance benchmark</Description>
  <Copyright>Copyright (c) Akka.NET Team</Copyright>
  <Authors>Akka.NET Team</Authors>
  <TargetFramework>$(NetTestVersion)</TargetFramework>
  <OutputType>Exe</OutputType>
  <IsPackable>false</IsPackable>
</PropertyGroup>

<PropertyGroup>
  <ServerGarbageCollection>true</ServerGarbageCollection>
  <TieredPGO>true</TieredPGO>
</PropertyGroup>

<ItemGroup>
  <ProjectReference Include="..\..\core\Akka.Remote\Akka.Remote.csproj" />
  <ProjectReference Include="..\..\contrib\serializers\Akka.Serialization.Hyperion\Akka.Serialization.Hyperion.csproj" />
  <ProjectReference Include="..\..\contrib\serializers\Akka.Serialization.MessagePack\Akka.Serialization.MessagePack.csproj" />
</ItemGroup>
  
</Project>
