//-----------------------------------------------------------------------
// <copyright file="SystemMessageDeliveryStage.cs" company="Akka.NET Project">
//     Copyright (C) 2009-2022 Lightbend Inc. <http://www.lightbend.com>
//     Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
// </copyright>
//-----------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using Akka.Dispatch.SysMsg;
using Akka.Event;
using Akka.Streams;
using Akka.Streams.Stage;

namespace Akka.Remote.Artery
{
    /// <summary>
    /// INTERNAL API.
    ///
    /// Outbound half of reliable system-message delivery (design.md gate G3, "Reliable
    /// system-message delivery"). A <c>GraphStage&lt;FlowShape&lt;IOutboundEnvelope, IOutboundEnvelope&gt;&gt;</c>
    /// materialized ONLY on the CONTROL stream (see <c>ArteryRemoting.MaterializeOutboundStream</c>),
    /// positioned BETWEEN <see cref="ArteryHeartbeatStage"/> and <see cref="OutboundHandshakeStage"/>
    /// -- upstream of the handshake stage so a freshly-wrapped <see cref="SystemMessageEnvelope"/> is
    /// gated by handshake completion exactly like every other control-stream element (it is held
    /// behind <see cref="OutboundHandshakeStage"/>'s <c>pendingMessage</c> until the association
    /// completes, never dropped).
    ///
    /// <para>
    /// <b>What it does to each element:</b>
    /// <list type="bullet">
    /// <item><description>
    /// <see cref="ISystemMessage"/> payload: assigns the next per-incarnation monotonic sequence
    /// number (starting at 1), wraps it as <see cref="SystemMessageEnvelope"/>
    /// (<c>ackReplyTo</c> = this system's own <see cref="IOutboundContext.LocalAddress"/>), buffers
    /// it (bounded, <c>system-message-buffer-size</c>) for possible resend, and emits the wrapped
    /// envelope downstream.
    /// </description></item>
    /// <item><description>
    /// <see cref="ClearSystemMessageDelivery"/>: intercepted and CONSUMED -- never forwarded to
    /// <c>Out</c>/the encoder. See that type's doc comments for why this is local-only (documented
    /// simplification vs. Pekko).
    /// </description></item>
    /// <item><description>
    /// Anything else (heartbeat, handshake-injected-via-side-channel n/a here, <see cref="Ack"/>/
    /// <see cref="Nack"/> replies generated by this system's OWN <see cref="SystemMessageAckerStage"/>
    /// replying to the peer, quarantine notices): passed through unchanged.
    /// </description></item>
    /// </list>
    /// </para>
    ///
    /// <para>
    /// <b>Ack/Nack consumption (async, cross-thread).</b> <see cref="Ack"/>/<see cref="Nack"/>
    /// REPLIES from the peer arrive on the INBOUND pipeline (a different materialized stream, a
    /// different execution context) and are broadcast via <c>ArteryRemoting</c>'s generic
    /// <see cref="IControlMessageSubscriber"/> mechanism (the same one heartbeat/quarantine use).
    /// This stage's logic subscribes itself (<see cref="IOutboundContext.SubscribeControl"/>) and
    /// bridges into its own single-threaded execution via <c>GetAsyncCallback</c> -- the standard,
    /// safe re-entry mechanism for a <c>GraphStageLogic</c> to be notified from another thread.
    /// </para>
    ///
    /// <para>
    /// <b>INVARIANT 3 -- the #6414 stale-ack guard (MANDATORY).</b> An incoming Ack/Nack is
    /// processed ONLY when its originating uid (decoded from the wire envelope's own header, passed
    /// alongside the message by <c>IControlMessageSubscriber.ControlMessageReceived</c>) equals this
    /// association's CURRENT <see cref="Artery.AssociationState.UniqueRemoteAddress"/> uid. A
    /// mismatch is EITHER a broadcast notification for a totally different association (globally
    /// shared subscription list) OR a late reply from a PRIOR incarnation of THIS association --
    /// either way it must never mutate the unacknowledged buffer or trigger a quarantine. This is the
    /// direct analogue of classic Akka.NET's #6414 fix in <c>AckedSendBuffer&lt;T&gt;.Acknowledge</c>
    /// (there guarded by a <c>CumulativeAck &gt; MaxSeq</c> seq comparison; here guarded structurally
    /// by uid, which Artery's simpler protocol makes possible).
    /// </para>
    ///
    /// <para>
    /// <b>Give-up (buffer overflow OR resend-timeout) -&gt; quarantine, never a silent drop
    /// (invariant 4).</b> If the unacknowledged buffer is full when a new system message arrives, OR
    /// if the resend timer observes the OLDEST unacknowledged entry has been waiting longer than
    /// <c>give-up-system-message-after</c>, this stage resets its own delivery state (seqNo back to
    /// 1, buffer emptied) AND calls <see cref="IOutboundContext.Quarantine"/>. Once quarantined,
    /// <c>ArteryRemoting.Send</c> stops routing FURTHER system messages for this uid at all (see that
    /// method's quarantine gate) -- so the immediate local reset is safe: nothing more will be sent
    /// under the just-given-up incarnation.
    /// </para>
    ///
    /// <para>
    /// <b>Resend-batch backpressure (documented simplification).</b> The resend timer only starts a
    /// NEW resend cycle when the previous one has fully drained downstream (<c>_outQueue</c> empty)
    /// -- this bounds queued-for-emission memory to at most one buffer's worth at a time, at the cost
    /// of occasionally skipping a tick under sustained backpressure (the NEXT tick will catch up).
    /// </para>
    /// </summary>
    internal sealed class SystemMessageDeliveryStage : GraphStage<FlowShape<IOutboundEnvelope, IOutboundEnvelope>>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessageDeliveryStage"/> class.
        /// </summary>
        /// <param name="context">The outbound association seam (local/remote address, association state, control send/subscribe, quarantine).</param>
        /// <param name="bufferCapacity">Maximum unacknowledged <see cref="SystemMessageEnvelope"/>s buffered for resend (<c>system-message-buffer-size</c>).</param>
        /// <param name="resendInterval">How often the whole unacknowledged window is resent (<c>system-message-resend-interval</c>).</param>
        /// <param name="giveUpAfter">How long the OLDEST unacknowledged entry may wait before giving up (<c>give-up-system-message-after</c>).</param>
        public SystemMessageDeliveryStage(IOutboundContext context, int bufferCapacity, TimeSpan resendInterval, TimeSpan giveUpAfter)
        {
            if (bufferCapacity <= 0)
                throw new ArgumentOutOfRangeException(nameof(bufferCapacity), bufferCapacity, "must be positive.");
            if (resendInterval <= TimeSpan.Zero)
                throw new ArgumentOutOfRangeException(nameof(resendInterval), resendInterval, "must be positive.");
            if (giveUpAfter <= TimeSpan.Zero)
                throw new ArgumentOutOfRangeException(nameof(giveUpAfter), giveUpAfter, "must be positive.");

            Context = context;
            BufferCapacity = bufferCapacity;
            ResendInterval = resendInterval;
            GiveUpAfter = giveUpAfter;
            Shape = new FlowShape<IOutboundEnvelope, IOutboundEnvelope>(In, Out);
        }

        public IOutboundContext Context { get; }
        public int BufferCapacity { get; }
        public TimeSpan ResendInterval { get; }
        public TimeSpan GiveUpAfter { get; }

        public Inlet<IOutboundEnvelope> In { get; } = new("SystemMessageDelivery.in");
        public Outlet<IOutboundEnvelope> Out { get; } = new("SystemMessageDelivery.out");

        public override FlowShape<IOutboundEnvelope, IOutboundEnvelope> Shape { get; }

        protected override GraphStageLogic CreateLogic(Attributes inheritedAttributes) => new Logic(this);

        private sealed class Logic : TimerGraphStageLogic, IInHandler, IOutHandler, IControlMessageSubscriber
        {
            private const string ResendTimerKey = "SystemMessageDelivery-Resend";

            private readonly SystemMessageDeliveryStage _stage;

            /// <summary>Unacknowledged envelopes, in ascending seq order (FIFO -- Ack/Nack pop a PREFIX).</summary>
            private readonly Queue<(long Seq, IOutboundEnvelope Envelope, DateTime SentAt)> _buffer = new();

            /// <summary>Elements queued for emission downstream (pass-through + freshly-wrapped + resend batches).</summary>
            private readonly Queue<IOutboundEnvelope> _outQueue = new();

            private long _nextSeq = 1;
            private int _currentIncarnation;
            private Action<(long OriginUid, object Message)>? _controlCallback;

            public Logic(SystemMessageDeliveryStage stage) : base(stage.Shape)
            {
                _stage = stage;
                SetHandler(stage.In, this);
                SetHandler(stage.Out, this);
            }

            public override void PreStart()
            {
                _currentIncarnation = _stage.Context.AssociationState.Incarnation;
                _controlCallback = GetAsyncCallback<(long OriginUid, object Message)>(HandleControlMessage);
                _stage.Context.SubscribeControl(this);
                ScheduleRepeatedly(ResendTimerKey, _stage.ResendInterval);
            }

            public override void PostStop() => _stage.Context.UnsubscribeControl(this);

            /// <inheritdoc/>
            /// <remarks>
            /// Called from the INBOUND pipeline's execution context (a different thread) -- must not
            /// touch any of this logic's mutable state directly. Bridges via the async callback
            /// obtained in <see cref="PreStart"/>.
            /// </remarks>
            void IControlMessageSubscriber.ControlMessageReceived(long originUid, object message) =>
                _controlCallback?.Invoke((originUid, message));

            private void HandleControlMessage((long OriginUid, object Message) evt)
            {
                // INVARIANT 3 / #6414 stale-ack guard -- see the type-level remarks. A mismatch is
                // silently ignored: it is either irrelevant (a different association's traffic,
                // broadcast globally) or a stale reply from a superseded incarnation of THIS one.
                var currentUid = _stage.Context.AssociationState.UniqueRemoteAddress?.Uid;

                switch (evt.Message)
                {
                    case Ack ack when evt.OriginUid == currentUid:
                        ProcessAck(ack.SeqNo);
                        break;

                    case Nack nack when evt.OriginUid == currentUid:
                        ProcessNack(nack.SeqNo);
                        break;
                }

                TryDeliver();
            }

            private void ProcessAck(long seqNo)
            {
                while (_buffer.Count > 0 && _buffer.Peek().Seq <= seqNo)
                    _buffer.Dequeue();
            }

            private void ProcessNack(long seqNo)
            {
                while (_buffer.Count > 0 && _buffer.Peek().Seq <= seqNo)
                    _buffer.Dequeue();

                // Immediate tail resend -- do not wait for the next resend-timer tick. Skipped if a
                // batch is already queued (bounds memory; see the type-level backpressure remarks).
                if (_buffer.Count > 0 && _outQueue.Count == 0)
                    foreach (var entry in _buffer)
                        _outQueue.Enqueue(entry.Envelope);
            }

            public void OnPush()
            {
                var elem = Grab(_stage.In);
                RefreshIncarnation();

                switch (elem.Message)
                {
                    case ClearSystemMessageDelivery clear:
                        if (clear.Incarnation >= _currentIncarnation)
                            ResetDeliveryState(clear.Incarnation);
                        // Local-only instruction -- never forwarded to Out/the encoder; see
                        // ClearSystemMessageDelivery's type-level remarks.
                        break;

                    case ISystemMessage systemMessage:
                        EnqueueSystemMessage(systemMessage, elem);
                        break;

                    default:
                        _outQueue.Enqueue(elem);
                        break;
                }

                DeliverOrPull();
            }

            private void EnqueueSystemMessage(ISystemMessage systemMessage, IOutboundEnvelope elem)
            {
                if (_buffer.Count >= _stage.BufferCapacity)
                {
                    GiveUp($"unacknowledged system-message buffer overflow (system-message-buffer-size = {_stage.BufferCapacity})");
                    Log.Warning(
                        "Dropping system message of type [{0}] to [{1}]: buffer overflow triggered give-up/quarantine.",
                        systemMessage.GetType(), _stage.Context.RemoteAddress);
                    return;
                }

                var seq = _nextSeq++;
                var envelope = new SystemMessageEnvelope(systemMessage, seq, _stage.Context.LocalAddress, elem.RecipientPath ?? string.Empty);
                var wrapped = new OutboundEnvelope(envelope, null, null);
                _buffer.Enqueue((seq, wrapped, DateTime.UtcNow));
                _outQueue.Enqueue(wrapped);
            }

            public void OnPull()
            {
                if (_outQueue.Count > 0)
                {
                    Push(_stage.Out, _outQueue.Dequeue());
                    return;
                }

                if (!IsClosed(_stage.In) && !HasBeenPulled(_stage.In))
                    Pull(_stage.In);
            }

            public void OnUpstreamFinish() => CompleteStage();

            public void OnUpstreamFailure(Exception e) => FailStage(e);

            public void OnDownstreamFinish(Exception cause) => InternalOnDownstreamFinish(cause);

            protected override void OnTimer(object timerKey)
            {
                if (!ResendTimerKey.Equals(timerKey))
                    return;

                RefreshIncarnation();

                if (_buffer.Count == 0)
                    return;

                var oldest = _buffer.Peek();
                if (DateTime.UtcNow - oldest.SentAt > _stage.GiveUpAfter)
                {
                    GiveUp($"give-up-system-message-after ({_stage.GiveUpAfter}) exceeded waiting for ack of seq [{oldest.Seq}]");
                    return;
                }

                // Only start a fresh resend cycle once the previous one has fully drained, and only
                // once the association is actually established (nothing useful to resend to a peer
                // whose uid isn't known yet -- OutboundHandshakeStage would hold it anyway, but no
                // sense growing _outQueue for it).
                if (_outQueue.Count == 0 && _stage.Context.AssociationState.UniqueRemoteAddress is not null)
                {
                    foreach (var entry in _buffer)
                        _outQueue.Enqueue(entry.Envelope);

                    DeliverOrPull();
                }
            }

            private void GiveUp(string reason)
            {
                Log.Warning(
                    "System-message delivery to [{0}] giving up: {1}. Quarantining the association.",
                    _stage.Context.RemoteAddress, reason);
                ResetDeliveryState(_currentIncarnation);
                _stage.Context.Quarantine();
            }

            /// <summary>
            /// Resets seqNo (back to 1) and empties the unacknowledged buffer -- idempotent, called
            /// both automatically (a genuinely new incarnation observed via
            /// <see cref="RefreshIncarnation"/>) and explicitly (<see cref="ClearSystemMessageDelivery"/>
            /// / give-up). Deliberately does NOT clear <see cref="_outQueue"/> -- any already-queued
            /// pass-through/resend elements are harmless to let drain (the control stream keeps
            /// flowing even once quarantined; see design.md's control-pierces-quarantine semantics).
            /// </summary>
            private void ResetDeliveryState(int incarnation)
            {
                _buffer.Clear();
                _nextSeq = 1;
                _currentIncarnation = incarnation;
            }

            /// <summary>
            /// Detects a remote restart (a genuinely NEW incarnation, i.e. a NEW peer uid completed
            /// a NEW handshake) purely by observing <see cref="Artery.AssociationState.Incarnation"/>
            /// advance -- design.md invariant 2 ("new incarnation -&gt; expected restarts at 1").
            /// Explicit quarantine of the CURRENT (unchanged) uid does NOT advance <c>Incarnation</c>
            /// by itself -- that case is handled by <see cref="ClearSystemMessageDelivery"/>/give-up
            /// instead (see their remarks).
            /// </summary>
            private void RefreshIncarnation()
            {
                var observed = _stage.Context.AssociationState.Incarnation;
                if (observed != _currentIncarnation)
                    ResetDeliveryState(observed);
            }

            private void DeliverOrPull()
            {
                if (_outQueue.Count > 0)
                {
                    if (IsAvailable(_stage.Out))
                        Push(_stage.Out, _outQueue.Dequeue());
                    return;
                }

                if (!IsClosed(_stage.In) && !HasBeenPulled(_stage.In))
                    Pull(_stage.In);
            }

            /// <summary>
            /// Pushes ONE queued element if <c>Out</c> currently has demand -- used from the async
            /// control-message callback, which runs OUTSIDE the normal push/pull reactive dance.
            /// </summary>
            private void TryDeliver()
            {
                if (_outQueue.Count > 0 && IsAvailable(_stage.Out))
                    Push(_stage.Out, _outQueue.Dequeue());
            }
        }
    }
}
