//-----------------------------------------------------------------------
// <copyright file="EnumerableActorName.cs" company="Akka.NET Project">
//     Copyright (C) 2009-2022 Lightbend Inc. <http://www.lightbend.com>
//     Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
// </copyright>
//-----------------------------------------------------------------------

using Akka.Util.Internal;

namespace Akka.Streams.Implementation
{
    /// <summary>
    /// Generator of sequentially numbered actor names.
    /// </summary>
    public abstract class EnumerableActorName
    {
        /// <summary>
        /// Creates a name generator that appends an increasing number to the supplied prefix.
        /// </summary>
        /// <param name="prefix">The prefix used for generated names.</param>
        /// <returns>A generator whose first name ends in <c>-0</c>.</returns>
        public static EnumerableActorName Create(string prefix)
        {
            return new EnumerableActorNameImpl(prefix, new AtomicCounterLong(0L));
        }

        /// <summary>
        /// Generates the next name by appending the next sequence number to the prefix.
        /// </summary>
        /// <returns>The next generated name.</returns>
        public abstract string Next();

        /// <summary>
        /// Creates a generator with a new prefix that continues the current sequence.
        /// </summary>
        /// <param name="newPrefix">The prefix to use for names generated by the copy.</param>
        /// <returns>A generator sharing this generator's sequence counter.</returns>
        public abstract EnumerableActorName Copy(string newPrefix);
    }

    /// <summary>
    /// Generates prefixed names from a shared atomic sequence counter.
    /// </summary>
    internal sealed class EnumerableActorNameImpl : EnumerableActorName
    {
        /// <summary>
        /// The prefix prepended to each generated sequence number.
        /// </summary>
        public readonly string Prefix;
        private readonly AtomicCounterLong _counter;

        /// <summary>
        /// Creates a generator using the supplied prefix and shared sequence counter.
        /// </summary>
        /// <param name="prefix">The prefix used for generated names.</param>
        /// <param name="counter">The counter incremented whenever a name is generated.</param>
        public EnumerableActorNameImpl(string prefix, AtomicCounterLong counter)
        {
            Prefix = prefix;
            _counter = counter;
        }

        /// <summary>
        /// Generates the next name by appending the next sequence number to the prefix.
        /// </summary>
        /// <returns>The next generated name.</returns>
        public override string Next() => Prefix + "-" + _counter.GetAndIncrement();

        /// <summary>
        /// Creates a generator with a new prefix that continues the current sequence.
        /// </summary>
        /// <param name="newPrefix">The prefix to use for names generated by the copy.</param>
        /// <returns>A generator sharing this generator's sequence counter.</returns>
        public override EnumerableActorName Copy(string newPrefix) => new EnumerableActorNameImpl(newPrefix, _counter);
    }
}
