version: "2.4"

services:
  akka-test:
    image: akka-test
    build: 
      context: .
    cpu_count: 1
    mem_limit: 1g
    environment:
      run_count: 2
      # to filter tests, uncomment
      # test_filter: "--filter FullyQualifiedName=Akka.Cluster.Tests.ClusterLogVerboseEnabledSpec.A_cluster_must_log_verbose_cluster_events_when_log_info_verbose_is_on"
      test_file: core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj