using System.Runtime.InteropServices;
﻿// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Akka")]
[assembly: AssemblyCopyrightAttribute("Copyright © Roger Asling 2013-2014")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersion("0.5.3.0")]
[assembly: AssemblyFileVersion("0.5.3.0")]
namespace System {
}
