namespace Akka.Serialization.Generator;

internal static class StaticCodes
{
    public const string Header =
"""
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Akka.NET serializer generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
""";
    
    public const string ExtensionsClass = Header +
""""

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Akka.Actor;
using Akka.Actor.Setup;
using Akka.Configuration;
using Akka.Serialization;

namespace Akka.Serialization.Generated;

public static partial class GeneratedSerializerExtensions
{
    private static SerializerDetails[] _serializerDetails = Array.Empty<SerializerDetails>();
    private static Dictionary<string, Type> _aliasMap;
    private static Dictionary<Type, string> _bindMap;
    
    public static ActorSystemSetup AddGeneratedSerializers(this ActorSystemSetup setup)
    {
        return setup.And(SerializationSetup.Create(sys =>
        {
            try
            {
                GenerateDetails(sys);
                return _serializerDetails.ToImmutableHashSet();
            }
            finally
            {
                _serializerDetails = Array.Empty<SerializerDetails>();
            }
        }));
    }
    
    public static Config GeneratedSerializerConfig()
    {
        try
        {
            GenerateHocon();

            var aliasSb = new StringBuilder();
            foreach (var kvp in _aliasMap)
            {
                aliasSb.AppendLine($"{kvp.Key} = \"{kvp.Value.AssemblyQualifiedName}\"");
            }

            var bindingSb = new StringBuilder();
            foreach (var kvp in _bindMap)
            {
                bindingSb.AppendLine($"\"{kvp.Key.AssemblyQualifiedName}\" = {kvp.Value}");
            }
            
            return 
$$"""
akka.actor {
  serializers {
{{aliasSb}}
  }
  serialization-bindings {
{{bindingSb}}
  }    
}
""";
        }
        finally
        {
            _aliasMap = null;
            _bindMap = null;
        }
    }

    public static Config AddGeneratedSerializers(this Config config)
    {
        return config.WithFallback(GeneratedSerializerConfig());
    }

    static partial void GenerateDetails(ExtendedActorSystem sys);
    static partial void GenerateHocon();
}
"""";
}

