// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ClusterMetricsMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akka.Cluster.Metrics.Serialization.Proto.Msg {

  /// <summary>Holder for reflection information generated from ClusterMetricsMessages.proto</summary>
  internal static partial class ClusterMetricsMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for ClusterMetricsMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClusterMetricsMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxDbHVzdGVyTWV0cmljc01lc3NhZ2VzLnByb3RvEixBa2thLkNsdXN0ZXIu",
            "TWV0cmljcy5TZXJpYWxpemF0aW9uLlByb3RvLk1zZxoWQ29udGFpbmVyRm9y",
            "bWF0cy5wcm90byKzAQoVTWV0cmljc0dvc3NpcEVudmVsb3BlEj4KBGZyb20Y",
            "ASABKAsyMC5Ba2thLlJlbW90ZS5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5B",
            "ZGRyZXNzRGF0YRJLCgZnb3NzaXAYAiABKAsyOy5Ba2thLkNsdXN0ZXIuTWV0",
            "cmljcy5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5NZXRyaWNzR29zc2lwEg0K",
            "BXJlcGx5GAMgASgIIr8BCg1NZXRyaWNzR29zc2lwEkYKDGFsbEFkZHJlc3Nl",
            "cxgBIAMoCzIwLkFra2EuUmVtb3RlLlNlcmlhbGl6YXRpb24uUHJvdG8uTXNn",
            "LkFkZHJlc3NEYXRhEhYKDmFsbE1ldHJpY05hbWVzGAIgAygJEk4KC25vZGVN",
            "ZXRyaWNzGAMgAygLMjkuQWtrYS5DbHVzdGVyLk1ldHJpY3MuU2VyaWFsaXph",
            "dGlvbi5Qcm90by5Nc2cuTm9kZU1ldHJpY3MizgQKC05vZGVNZXRyaWNzEhQK",
            "DGFkZHJlc3NJbmRleBgBIAEoBRIRCgl0aW1lc3RhbXAYAiABKAMSUQoHbWV0",
            "cmljcxgDIAMoCzJALkFra2EuQ2x1c3Rlci5NZXRyaWNzLlNlcmlhbGl6YXRp",
            "b24uUHJvdG8uTXNnLk5vZGVNZXRyaWNzLk1ldHJpYxqSAQoGTnVtYmVyElIK",
            "BHR5cGUYASABKA4yRC5Ba2thLkNsdXN0ZXIuTWV0cmljcy5TZXJpYWxpemF0",
            "aW9uLlByb3RvLk1zZy5Ob2RlTWV0cmljcy5OdW1iZXJUeXBlEg8KB3ZhbHVl",
            "MzIYAiABKA0SDwoHdmFsdWU2NBgDIAEoBBISCgpzZXJpYWxpemVkGAQgASgM",
            "GiQKBEVXTUESDQoFdmFsdWUYASABKAESDQoFYWxwaGEYAiABKAEauwEKBk1l",
            "dHJpYxIRCgluYW1lSW5kZXgYASABKAUSUAoGbnVtYmVyGAIgASgLMkAuQWtr",
            "YS5DbHVzdGVyLk1ldHJpY3MuU2VyaWFsaXphdGlvbi5Qcm90by5Nc2cuTm9k",
            "ZU1ldHJpY3MuTnVtYmVyEkwKBGV3bWEYAyABKAsyPi5Ba2thLkNsdXN0ZXIu",
            "TWV0cmljcy5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5Ob2RlTWV0cmljcy5F",
            "V01BIkoKCk51bWJlclR5cGUSDgoKU2VyaWFsaXplZBAAEgoKBkRvdWJsZRAB",
            "EgkKBUZsb2F0EAISCwoHSW50ZWdlchADEggKBExvbmcQBCK/AQoZQWRhcHRp",
            "dmVMb2FkQmFsYW5jaW5nUG9vbBJWCg9tZXRyaWNzU2VsZWN0b3IYASABKAsy",
            "PS5Ba2thLkNsdXN0ZXIuTWV0cmljcy5TZXJpYWxpemF0aW9uLlByb3RvLk1z",
            "Zy5NZXRyaWNzU2VsZWN0b3ISFQoNbnJPZkluc3RhbmNlcxgCIAEoDRIYChBy",
            "b3V0ZXJEaXNwYXRjaGVyGAMgASgJEhkKEXVzZVBvb2xEaXNwYXRjaGVyGAQg",
            "ASgIIkcKD01ldHJpY3NTZWxlY3RvchIUCgxzZXJpYWxpemVySWQYASABKA0S",
            "EAoIbWFuaWZlc3QYAiABKAkSDAoEZGF0YRgDIAEoDCJmChJNaXhNZXRyaWNz",
            "U2VsZWN0b3ISUAoJc2VsZWN0b3JzGAEgAygLMj0uQWtrYS5DbHVzdGVyLk1l",
            "dHJpY3MuU2VyaWFsaXphdGlvbi5Qcm90by5Nc2cuTWV0cmljc1NlbGVjdG9y",
            "QgJIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Akka.Remote.Serialization.Proto.Msg.ContainerFormatsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossipEnvelope), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossipEnvelope.Parser, new[]{ "From", "Gossip", "Reply" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip.Parser, new[]{ "AllAddresses", "AllMetricNames", "NodeMetrics" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Parser, new[]{ "AddressIndex", "Timestamp", "Metrics" }, null, new[]{ typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number.Parser, new[]{ "Type", "Value32", "Value64", "Serialized" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA.Parser, new[]{ "Value", "Alpha" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric.Parser, new[]{ "NameIndex", "Number", "Ewma" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.AdaptiveLoadBalancingPool), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.AdaptiveLoadBalancingPool.Parser, new[]{ "MetricsSelector", "NrOfInstances", "RouterDispatcher", "UsePoolDispatcher" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector.Parser, new[]{ "SerializerId", "Manifest", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MixMetricsSelector), global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MixMetricsSelector.Parser, new[]{ "Selectors" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Metrics Gossip Envelope
  /// </summary>
  internal sealed partial class MetricsGossipEnvelope : pb::IMessage<MetricsGossipEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MetricsGossipEnvelope> _parser = new pb::MessageParser<MetricsGossipEnvelope>(() => new MetricsGossipEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MetricsGossipEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.ClusterMetricsMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsGossipEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsGossipEnvelope(MetricsGossipEnvelope other) : this() {
      from_ = other.from_ != null ? other.from_.Clone() : null;
      gossip_ = other.gossip_ != null ? other.gossip_.Clone() : null;
      reply_ = other.reply_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsGossipEnvelope Clone() {
      return new MetricsGossipEnvelope(this);
    }

    /// <summary>Field number for the "from" field.</summary>
    public const int FromFieldNumber = 1;
    private global::Akka.Remote.Serialization.Proto.Msg.AddressData from_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Akka.Remote.Serialization.Proto.Msg.AddressData From {
      get { return from_; }
      set {
        from_ = value;
      }
    }

    /// <summary>Field number for the "gossip" field.</summary>
    public const int GossipFieldNumber = 2;
    private global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip gossip_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip Gossip {
      get { return gossip_; }
      set {
        gossip_ = value;
      }
    }

    /// <summary>Field number for the "reply" field.</summary>
    public const int ReplyFieldNumber = 3;
    private bool reply_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Reply {
      get { return reply_; }
      set {
        reply_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MetricsGossipEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MetricsGossipEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(From, other.From)) return false;
      if (!object.Equals(Gossip, other.Gossip)) return false;
      if (Reply != other.Reply) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (from_ != null) hash ^= From.GetHashCode();
      if (gossip_ != null) hash ^= Gossip.GetHashCode();
      if (Reply != false) hash ^= Reply.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (from_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(From);
      }
      if (gossip_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Gossip);
      }
      if (Reply != false) {
        output.WriteRawTag(24);
        output.WriteBool(Reply);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (from_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(From);
      }
      if (gossip_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Gossip);
      }
      if (Reply != false) {
        output.WriteRawTag(24);
        output.WriteBool(Reply);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (from_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(From);
      }
      if (gossip_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gossip);
      }
      if (Reply != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MetricsGossipEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.from_ != null) {
        if (from_ == null) {
          From = new global::Akka.Remote.Serialization.Proto.Msg.AddressData();
        }
        From.MergeFrom(other.From);
      }
      if (other.gossip_ != null) {
        if (gossip_ == null) {
          Gossip = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip();
        }
        Gossip.MergeFrom(other.Gossip);
      }
      if (other.Reply != false) {
        Reply = other.Reply;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (from_ == null) {
              From = new global::Akka.Remote.Serialization.Proto.Msg.AddressData();
            }
            input.ReadMessage(From);
            break;
          }
          case 18: {
            if (gossip_ == null) {
              Gossip = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip();
            }
            input.ReadMessage(Gossip);
            break;
          }
          case 24: {
            Reply = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (from_ == null) {
              From = new global::Akka.Remote.Serialization.Proto.Msg.AddressData();
            }
            input.ReadMessage(From);
            break;
          }
          case 18: {
            if (gossip_ == null) {
              Gossip = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsGossip();
            }
            input.ReadMessage(Gossip);
            break;
          }
          case 24: {
            Reply = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// Metrics Gossip
  /// </summary>
  internal sealed partial class MetricsGossip : pb::IMessage<MetricsGossip>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MetricsGossip> _parser = new pb::MessageParser<MetricsGossip>(() => new MetricsGossip());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MetricsGossip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.ClusterMetricsMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsGossip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsGossip(MetricsGossip other) : this() {
      allAddresses_ = other.allAddresses_.Clone();
      allMetricNames_ = other.allMetricNames_.Clone();
      nodeMetrics_ = other.nodeMetrics_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsGossip Clone() {
      return new MetricsGossip(this);
    }

    /// <summary>Field number for the "allAddresses" field.</summary>
    public const int AllAddressesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Akka.Remote.Serialization.Proto.Msg.AddressData> _repeated_allAddresses_codec
        = pb::FieldCodec.ForMessage(10, global::Akka.Remote.Serialization.Proto.Msg.AddressData.Parser);
    private readonly pbc::RepeatedField<global::Akka.Remote.Serialization.Proto.Msg.AddressData> allAddresses_ = new pbc::RepeatedField<global::Akka.Remote.Serialization.Proto.Msg.AddressData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Akka.Remote.Serialization.Proto.Msg.AddressData> AllAddresses {
      get { return allAddresses_; }
    }

    /// <summary>Field number for the "allMetricNames" field.</summary>
    public const int AllMetricNamesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_allMetricNames_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> allMetricNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> AllMetricNames {
      get { return allMetricNames_; }
    }

    /// <summary>Field number for the "nodeMetrics" field.</summary>
    public const int NodeMetricsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics> _repeated_nodeMetrics_codec
        = pb::FieldCodec.ForMessage(26, global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics> nodeMetrics_ = new pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics> NodeMetrics {
      get { return nodeMetrics_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MetricsGossip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MetricsGossip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!allAddresses_.Equals(other.allAddresses_)) return false;
      if(!allMetricNames_.Equals(other.allMetricNames_)) return false;
      if(!nodeMetrics_.Equals(other.nodeMetrics_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= allAddresses_.GetHashCode();
      hash ^= allMetricNames_.GetHashCode();
      hash ^= nodeMetrics_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      allAddresses_.WriteTo(output, _repeated_allAddresses_codec);
      allMetricNames_.WriteTo(output, _repeated_allMetricNames_codec);
      nodeMetrics_.WriteTo(output, _repeated_nodeMetrics_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      allAddresses_.WriteTo(ref output, _repeated_allAddresses_codec);
      allMetricNames_.WriteTo(ref output, _repeated_allMetricNames_codec);
      nodeMetrics_.WriteTo(ref output, _repeated_nodeMetrics_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += allAddresses_.CalculateSize(_repeated_allAddresses_codec);
      size += allMetricNames_.CalculateSize(_repeated_allMetricNames_codec);
      size += nodeMetrics_.CalculateSize(_repeated_nodeMetrics_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MetricsGossip other) {
      if (other == null) {
        return;
      }
      allAddresses_.Add(other.allAddresses_);
      allMetricNames_.Add(other.allMetricNames_);
      nodeMetrics_.Add(other.nodeMetrics_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            allAddresses_.AddEntriesFrom(input, _repeated_allAddresses_codec);
            break;
          }
          case 18: {
            allMetricNames_.AddEntriesFrom(input, _repeated_allMetricNames_codec);
            break;
          }
          case 26: {
            nodeMetrics_.AddEntriesFrom(input, _repeated_nodeMetrics_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            allAddresses_.AddEntriesFrom(ref input, _repeated_allAddresses_codec);
            break;
          }
          case 18: {
            allMetricNames_.AddEntriesFrom(ref input, _repeated_allMetricNames_codec);
            break;
          }
          case 26: {
            nodeMetrics_.AddEntriesFrom(ref input, _repeated_nodeMetrics_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// Node Metrics
  /// </summary>
  internal sealed partial class NodeMetrics : pb::IMessage<NodeMetrics>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NodeMetrics> _parser = new pb::MessageParser<NodeMetrics>(() => new NodeMetrics());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NodeMetrics> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.ClusterMetricsMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeMetrics() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeMetrics(NodeMetrics other) : this() {
      addressIndex_ = other.addressIndex_;
      timestamp_ = other.timestamp_;
      metrics_ = other.metrics_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeMetrics Clone() {
      return new NodeMetrics(this);
    }

    /// <summary>Field number for the "addressIndex" field.</summary>
    public const int AddressIndexFieldNumber = 1;
    private int addressIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AddressIndex {
      get { return addressIndex_; }
      set {
        addressIndex_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 2;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "metrics" field.</summary>
    public const int MetricsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric> _repeated_metrics_codec
        = pb::FieldCodec.ForMessage(26, global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric> metrics_ = new pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Metric> Metrics {
      get { return metrics_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NodeMetrics);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NodeMetrics other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AddressIndex != other.AddressIndex) return false;
      if (Timestamp != other.Timestamp) return false;
      if(!metrics_.Equals(other.metrics_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AddressIndex != 0) hash ^= AddressIndex.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      hash ^= metrics_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AddressIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AddressIndex);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Timestamp);
      }
      metrics_.WriteTo(output, _repeated_metrics_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AddressIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AddressIndex);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Timestamp);
      }
      metrics_.WriteTo(ref output, _repeated_metrics_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AddressIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AddressIndex);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      size += metrics_.CalculateSize(_repeated_metrics_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NodeMetrics other) {
      if (other == null) {
        return;
      }
      if (other.AddressIndex != 0) {
        AddressIndex = other.AddressIndex;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      metrics_.Add(other.metrics_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AddressIndex = input.ReadInt32();
            break;
          }
          case 16: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 26: {
            metrics_.AddEntriesFrom(input, _repeated_metrics_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AddressIndex = input.ReadInt32();
            break;
          }
          case 16: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 26: {
            metrics_.AddEntriesFrom(ref input, _repeated_metrics_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the NodeMetrics message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      internal enum NumberType {
        [pbr::OriginalName("Serialized")] Serialized = 0,
        [pbr::OriginalName("Double")] Double = 1,
        [pbr::OriginalName("Float")] Float = 2,
        [pbr::OriginalName("Integer")] Integer = 3,
        [pbr::OriginalName("Long")] Long = 4,
      }

      internal sealed partial class Number : pb::IMessage<Number>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Number> _parser = new pb::MessageParser<Number>(() => new Number());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Number> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Number() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Number(Number other) : this() {
          type_ = other.type_;
          value32_ = other.value32_;
          value64_ = other.value64_;
          serialized_ = other.serialized_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Number Clone() {
          return new Number(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType type_ = global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType.Serialized;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "value32" field.</summary>
        public const int Value32FieldNumber = 2;
        private uint value32_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Value32 {
          get { return value32_; }
          set {
            value32_ = value;
          }
        }

        /// <summary>Field number for the "value64" field.</summary>
        public const int Value64FieldNumber = 3;
        private ulong value64_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Value64 {
          get { return value64_; }
          set {
            value64_ = value;
          }
        }

        /// <summary>Field number for the "serialized" field.</summary>
        public const int SerializedFieldNumber = 4;
        private pb::ByteString serialized_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Serialized {
          get { return serialized_; }
          set {
            serialized_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Number);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Number other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Type != other.Type) return false;
          if (Value32 != other.Value32) return false;
          if (Value64 != other.Value64) return false;
          if (Serialized != other.Serialized) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Type != global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType.Serialized) hash ^= Type.GetHashCode();
          if (Value32 != 0) hash ^= Value32.GetHashCode();
          if (Value64 != 0UL) hash ^= Value64.GetHashCode();
          if (Serialized.Length != 0) hash ^= Serialized.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Type != global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType.Serialized) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Type);
          }
          if (Value32 != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Value32);
          }
          if (Value64 != 0UL) {
            output.WriteRawTag(24);
            output.WriteUInt64(Value64);
          }
          if (Serialized.Length != 0) {
            output.WriteRawTag(34);
            output.WriteBytes(Serialized);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Type != global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType.Serialized) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Type);
          }
          if (Value32 != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Value32);
          }
          if (Value64 != 0UL) {
            output.WriteRawTag(24);
            output.WriteUInt64(Value64);
          }
          if (Serialized.Length != 0) {
            output.WriteRawTag(34);
            output.WriteBytes(Serialized);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Type != global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType.Serialized) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (Value32 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Value32);
          }
          if (Value64 != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Value64);
          }
          if (Serialized.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Serialized);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Number other) {
          if (other == null) {
            return;
          }
          if (other.Type != global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType.Serialized) {
            Type = other.Type;
          }
          if (other.Value32 != 0) {
            Value32 = other.Value32;
          }
          if (other.Value64 != 0UL) {
            Value64 = other.Value64;
          }
          if (other.Serialized.Length != 0) {
            Serialized = other.Serialized;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Type = (global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType) input.ReadEnum();
                break;
              }
              case 16: {
                Value32 = input.ReadUInt32();
                break;
              }
              case 24: {
                Value64 = input.ReadUInt64();
                break;
              }
              case 34: {
                Serialized = input.ReadBytes();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Type = (global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.NumberType) input.ReadEnum();
                break;
              }
              case 16: {
                Value32 = input.ReadUInt32();
                break;
              }
              case 24: {
                Value64 = input.ReadUInt64();
                break;
              }
              case 34: {
                Serialized = input.ReadBytes();
                break;
              }
            }
          }
        }
        #endif

      }

      internal sealed partial class EWMA : pb::IMessage<EWMA>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<EWMA> _parser = new pb::MessageParser<EWMA>(() => new EWMA());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EWMA> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EWMA() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EWMA(EWMA other) : this() {
          value_ = other.value_;
          alpha_ = other.alpha_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EWMA Clone() {
          return new EWMA(this);
        }

        /// <summary>Field number for the "value" field.</summary>
        public const int ValueFieldNumber = 1;
        private double value_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Value {
          get { return value_; }
          set {
            value_ = value;
          }
        }

        /// <summary>Field number for the "alpha" field.</summary>
        public const int AlphaFieldNumber = 2;
        private double alpha_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Alpha {
          get { return alpha_; }
          set {
            alpha_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EWMA);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EWMA other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Alpha, other.Alpha)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
          if (Alpha != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Alpha);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Value != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(Value);
          }
          if (Alpha != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Alpha);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Value != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(Value);
          }
          if (Alpha != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Alpha);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Value != 0D) {
            size += 1 + 8;
          }
          if (Alpha != 0D) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EWMA other) {
          if (other == null) {
            return;
          }
          if (other.Value != 0D) {
            Value = other.Value;
          }
          if (other.Alpha != 0D) {
            Alpha = other.Alpha;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 9: {
                Value = input.ReadDouble();
                break;
              }
              case 17: {
                Alpha = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 9: {
                Value = input.ReadDouble();
                break;
              }
              case 17: {
                Alpha = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

      internal sealed partial class Metric : pb::IMessage<Metric>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Metric> _parser = new pb::MessageParser<Metric>(() => new Metric());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Metric> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Metric() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Metric(Metric other) : this() {
          nameIndex_ = other.nameIndex_;
          number_ = other.number_ != null ? other.number_.Clone() : null;
          ewma_ = other.ewma_ != null ? other.ewma_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Metric Clone() {
          return new Metric(this);
        }

        /// <summary>Field number for the "nameIndex" field.</summary>
        public const int NameIndexFieldNumber = 1;
        private int nameIndex_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int NameIndex {
          get { return nameIndex_; }
          set {
            nameIndex_ = value;
          }
        }

        /// <summary>Field number for the "number" field.</summary>
        public const int NumberFieldNumber = 2;
        private global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number number_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number Number {
          get { return number_; }
          set {
            number_ = value;
          }
        }

        /// <summary>Field number for the "ewma" field.</summary>
        public const int EwmaFieldNumber = 3;
        private global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA ewma_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA Ewma {
          get { return ewma_; }
          set {
            ewma_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Metric);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Metric other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (NameIndex != other.NameIndex) return false;
          if (!object.Equals(Number, other.Number)) return false;
          if (!object.Equals(Ewma, other.Ewma)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (NameIndex != 0) hash ^= NameIndex.GetHashCode();
          if (number_ != null) hash ^= Number.GetHashCode();
          if (ewma_ != null) hash ^= Ewma.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (NameIndex != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(NameIndex);
          }
          if (number_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Number);
          }
          if (ewma_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Ewma);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (NameIndex != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(NameIndex);
          }
          if (number_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Number);
          }
          if (ewma_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Ewma);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (NameIndex != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NameIndex);
          }
          if (number_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Number);
          }
          if (ewma_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ewma);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Metric other) {
          if (other == null) {
            return;
          }
          if (other.NameIndex != 0) {
            NameIndex = other.NameIndex;
          }
          if (other.number_ != null) {
            if (number_ == null) {
              Number = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number();
            }
            Number.MergeFrom(other.Number);
          }
          if (other.ewma_ != null) {
            if (ewma_ == null) {
              Ewma = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA();
            }
            Ewma.MergeFrom(other.Ewma);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                NameIndex = input.ReadInt32();
                break;
              }
              case 18: {
                if (number_ == null) {
                  Number = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number();
                }
                input.ReadMessage(Number);
                break;
              }
              case 26: {
                if (ewma_ == null) {
                  Ewma = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA();
                }
                input.ReadMessage(Ewma);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                NameIndex = input.ReadInt32();
                break;
              }
              case 18: {
                if (number_ == null) {
                  Number = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.Number();
                }
                input.ReadMessage(Number);
                break;
              }
              case 26: {
                if (ewma_ == null) {
                  Ewma = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.NodeMetrics.Types.EWMA();
                }
                input.ReadMessage(Ewma);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  internal sealed partial class AdaptiveLoadBalancingPool : pb::IMessage<AdaptiveLoadBalancingPool>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AdaptiveLoadBalancingPool> _parser = new pb::MessageParser<AdaptiveLoadBalancingPool>(() => new AdaptiveLoadBalancingPool());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AdaptiveLoadBalancingPool> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.ClusterMetricsMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AdaptiveLoadBalancingPool() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AdaptiveLoadBalancingPool(AdaptiveLoadBalancingPool other) : this() {
      metricsSelector_ = other.metricsSelector_ != null ? other.metricsSelector_.Clone() : null;
      nrOfInstances_ = other.nrOfInstances_;
      routerDispatcher_ = other.routerDispatcher_;
      usePoolDispatcher_ = other.usePoolDispatcher_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AdaptiveLoadBalancingPool Clone() {
      return new AdaptiveLoadBalancingPool(this);
    }

    /// <summary>Field number for the "metricsSelector" field.</summary>
    public const int MetricsSelectorFieldNumber = 1;
    private global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector metricsSelector_;
    /// <summary>
    /// omitted if default
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector MetricsSelector {
      get { return metricsSelector_; }
      set {
        metricsSelector_ = value;
      }
    }

    /// <summary>Field number for the "nrOfInstances" field.</summary>
    public const int NrOfInstancesFieldNumber = 2;
    private uint nrOfInstances_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NrOfInstances {
      get { return nrOfInstances_; }
      set {
        nrOfInstances_ = value;
      }
    }

    /// <summary>Field number for the "routerDispatcher" field.</summary>
    public const int RouterDispatcherFieldNumber = 3;
    private string routerDispatcher_ = "";
    /// <summary>
    /// omitted if default
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RouterDispatcher {
      get { return routerDispatcher_; }
      set {
        routerDispatcher_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "usePoolDispatcher" field.</summary>
    public const int UsePoolDispatcherFieldNumber = 4;
    private bool usePoolDispatcher_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UsePoolDispatcher {
      get { return usePoolDispatcher_; }
      set {
        usePoolDispatcher_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AdaptiveLoadBalancingPool);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AdaptiveLoadBalancingPool other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MetricsSelector, other.MetricsSelector)) return false;
      if (NrOfInstances != other.NrOfInstances) return false;
      if (RouterDispatcher != other.RouterDispatcher) return false;
      if (UsePoolDispatcher != other.UsePoolDispatcher) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (metricsSelector_ != null) hash ^= MetricsSelector.GetHashCode();
      if (NrOfInstances != 0) hash ^= NrOfInstances.GetHashCode();
      if (RouterDispatcher.Length != 0) hash ^= RouterDispatcher.GetHashCode();
      if (UsePoolDispatcher != false) hash ^= UsePoolDispatcher.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (metricsSelector_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MetricsSelector);
      }
      if (NrOfInstances != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(NrOfInstances);
      }
      if (RouterDispatcher.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RouterDispatcher);
      }
      if (UsePoolDispatcher != false) {
        output.WriteRawTag(32);
        output.WriteBool(UsePoolDispatcher);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (metricsSelector_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MetricsSelector);
      }
      if (NrOfInstances != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(NrOfInstances);
      }
      if (RouterDispatcher.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RouterDispatcher);
      }
      if (UsePoolDispatcher != false) {
        output.WriteRawTag(32);
        output.WriteBool(UsePoolDispatcher);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (metricsSelector_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MetricsSelector);
      }
      if (NrOfInstances != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NrOfInstances);
      }
      if (RouterDispatcher.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RouterDispatcher);
      }
      if (UsePoolDispatcher != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AdaptiveLoadBalancingPool other) {
      if (other == null) {
        return;
      }
      if (other.metricsSelector_ != null) {
        if (metricsSelector_ == null) {
          MetricsSelector = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector();
        }
        MetricsSelector.MergeFrom(other.MetricsSelector);
      }
      if (other.NrOfInstances != 0) {
        NrOfInstances = other.NrOfInstances;
      }
      if (other.RouterDispatcher.Length != 0) {
        RouterDispatcher = other.RouterDispatcher;
      }
      if (other.UsePoolDispatcher != false) {
        UsePoolDispatcher = other.UsePoolDispatcher;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (metricsSelector_ == null) {
              MetricsSelector = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector();
            }
            input.ReadMessage(MetricsSelector);
            break;
          }
          case 16: {
            NrOfInstances = input.ReadUInt32();
            break;
          }
          case 26: {
            RouterDispatcher = input.ReadString();
            break;
          }
          case 32: {
            UsePoolDispatcher = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (metricsSelector_ == null) {
              MetricsSelector = new global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector();
            }
            input.ReadMessage(MetricsSelector);
            break;
          }
          case 16: {
            NrOfInstances = input.ReadUInt32();
            break;
          }
          case 26: {
            RouterDispatcher = input.ReadString();
            break;
          }
          case 32: {
            UsePoolDispatcher = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// couldn't figure out how to import Payload
  /// </summary>
  internal sealed partial class MetricsSelector : pb::IMessage<MetricsSelector>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MetricsSelector> _parser = new pb::MessageParser<MetricsSelector>(() => new MetricsSelector());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MetricsSelector> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.ClusterMetricsMessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsSelector() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsSelector(MetricsSelector other) : this() {
      serializerId_ = other.serializerId_;
      manifest_ = other.manifest_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MetricsSelector Clone() {
      return new MetricsSelector(this);
    }

    /// <summary>Field number for the "serializerId" field.</summary>
    public const int SerializerIdFieldNumber = 1;
    private uint serializerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SerializerId {
      get { return serializerId_; }
      set {
        serializerId_ = value;
      }
    }

    /// <summary>Field number for the "manifest" field.</summary>
    public const int ManifestFieldNumber = 2;
    private string manifest_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Manifest {
      get { return manifest_; }
      set {
        manifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MetricsSelector);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MetricsSelector other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SerializerId != other.SerializerId) return false;
      if (Manifest != other.Manifest) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SerializerId != 0) hash ^= SerializerId.GetHashCode();
      if (Manifest.Length != 0) hash ^= Manifest.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SerializerId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SerializerId);
      }
      if (Manifest.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Manifest);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SerializerId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SerializerId);
      }
      if (Manifest.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Manifest);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SerializerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SerializerId);
      }
      if (Manifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Manifest);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MetricsSelector other) {
      if (other == null) {
        return;
      }
      if (other.SerializerId != 0) {
        SerializerId = other.SerializerId;
      }
      if (other.Manifest.Length != 0) {
        Manifest = other.Manifest;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SerializerId = input.ReadUInt32();
            break;
          }
          case 18: {
            Manifest = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SerializerId = input.ReadUInt32();
            break;
          }
          case 18: {
            Manifest = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class MixMetricsSelector : pb::IMessage<MixMetricsSelector>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MixMetricsSelector> _parser = new pb::MessageParser<MixMetricsSelector>(() => new MixMetricsSelector());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MixMetricsSelector> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Cluster.Metrics.Serialization.Proto.Msg.ClusterMetricsMessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MixMetricsSelector() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MixMetricsSelector(MixMetricsSelector other) : this() {
      selectors_ = other.selectors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MixMetricsSelector Clone() {
      return new MixMetricsSelector(this);
    }

    /// <summary>Field number for the "selectors" field.</summary>
    public const int SelectorsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector> _repeated_selectors_codec
        = pb::FieldCodec.ForMessage(10, global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector.Parser);
    private readonly pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector> selectors_ = new pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Akka.Cluster.Metrics.Serialization.Proto.Msg.MetricsSelector> Selectors {
      get { return selectors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MixMetricsSelector);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MixMetricsSelector other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!selectors_.Equals(other.selectors_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= selectors_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      selectors_.WriteTo(output, _repeated_selectors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      selectors_.WriteTo(ref output, _repeated_selectors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += selectors_.CalculateSize(_repeated_selectors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MixMetricsSelector other) {
      if (other == null) {
        return;
      }
      selectors_.Add(other.selectors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            selectors_.AddEntriesFrom(input, _repeated_selectors_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            selectors_.AddEntriesFrom(ref input, _repeated_selectors_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
