name: Documentation PRs

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  spellcheck:
    name: "Spell check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: "12"
      - run: npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./docs/cSpell.json "docs/**/*.md"
        name: run cSpell
